Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2021-11, with the labels that each got.

#400 fix: ngo-pre.3 asset fixes for NetworkAnimator
  Assets/BossRoom/Prefabs/Character/Imp.prefab
  Assets/BossRoom/Prefabs/Character/ImpBoss.prefab
  Assets/BossRoom/Prefabs/Character/PlayerAvatar.prefab
  Assets/BossRoom/Scripts/NetworkAnimator.meta
  Assets/BossRoom/Scripts/NetworkAnimator/BossRoomNetworkAnimator.asmdef
  Assets/BossRoom/Scripts/NetworkAnimator/BossRoomNetworkAnimator.asmdef.meta
  Assets/BossRoom/Scripts/NetworkAnimator/NetworkAnimator.cs
  Assets/BossRoom/Scripts/NetworkAnimator/NetworkAnimator.cs.meta
  Assets/BossRoom/Scripts/Server/com.unity.multiplayer.samples.bossroom.server.asmdef
  Packages/manifest.json
  Packages/packages-lock.json
Labels: URGENT, One More Review

#405 fix: bug with network object pool global object id hash
  Assets/BossRoom/Scenes/BossRoom.unity
Labels: Good to Merge

#406 Fix: arrows despawning error while switching scenes
  Assets/BossRoom/Scripts/Server/Game/Action/LaunchProjectileAction.cs
Labels: Easy, Good to Merge

#402 Sam/feature/updating photon to latest
  Assets/BossRoom/Prefabs/NetworkingManager.prefab
  Packages/packages-lock.json
Labels: Good to Merge

#413 Fix/ready button text change
  Assets/BossRoom/Scenes/CharSelect.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientCharSelectState.cs
Labels: Easy, Good to Merge

#409 fix: invincibility counter reset on cancel, animator invincibility paramet…
  Assets/BossRoom/Models/Animation Controllers/CharacterSetController.controller
  Assets/BossRoom/Scripts/Server/Game/Action/ChargedShieldAction.cs
Labels: Good to Merge

#410 fix: replace mlapi references with ngo
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: Easy, Good to Merge

#414 Shader Graph Toon Shader
  Assets/BossRoom/Material/Characters/Toon/Hair_Archer_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Archer_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Mage_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Mage_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Rogue_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Rogue_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Tank_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Tank_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Archer_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Archer_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Boss.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Imp.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Mage_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Mage_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Rogue_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Rogue_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Tank_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Tank_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Archer.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Boss.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Imp.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Mage_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Mage_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Rogue.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Tank.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Archer.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Imp.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Mage.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Rogue.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Tank.mat
  Assets/BossRoom/Shaders/MainLight.hlsl
  Assets/BossRoom/Shaders/MainLight.hlsl.meta
  Assets/BossRoom/Shaders/SG_Toon.shadergraph
  Assets/BossRoom/Shaders/SG_Toon.shadergraph.meta
  Assets/BossRoom/Shaders/UnityToonShader.meta
  Assets/BossRoom/Shaders/UnityToonShader/ShadowReceiver.shader
  Assets/BossRoom/Shaders/UnityToonShader/ShadowReceiver.shader.meta
  Assets/BossRoom/Shaders/UnityToonShader/Toon.shader
  Assets/BossRoom/Shaders/UnityToonShader/Toon.shader.meta
  Assets/BossRoom/Shaders/UnityToonShader/ToonComplete.shader
  Assets/BossRoom/Shaders/UnityToonShader/ToonComplete.shader.meta
  Assets/BossRoom/Shaders/UnityToonShader/license.txt
  Assets/BossRoom/Shaders/UnityToonShader/license.txt.meta
Labels: URGENT, Easy, Good to Merge, priority:highest, type:feature

#416 Updated char select background prefab
  Assets/BossRoom/Prefabs/UI/CharSel_Background.prefab
  Assets/BossRoom/Scenes/CharSelect.unity
  Assets/BossRoom/Scenes/MainMenu.unity
Labels: URGENT, Easy, Good to Merge

#412 feat: warning when using simulated latency
  Assets/BossRoom/Scripts/Shared/Game/UI/Editor/NetworkLatencyWarning.cs
  Assets/BossRoom/Scripts/Shared/com.unity.multiplayer.samples.bossroom.shared.asmdef
Labels: Good to Merge

#411 feat: player hierarchy QoL updates, anim event listener added for player anim events
  Assets/BossRoom/Prefabs/CharGFX/BossGraphics.prefab
  Assets/BossRoom/Prefabs/CharGFX/CharacterGraphics/CharacterSelect/PlayerGraphics_Archer_Boy_CharacterSelect.prefab
  Assets/BossRoom/Prefabs/CharGFX/CharacterGraphics/CharacterSelect/PlayerGraphics_Archer_Girl_CharacterSelect.prefab
  Assets/BossRoom/Prefabs/CharGFX/CharacterGraphics/CharacterSelect/PlayerGraphics_Mage_Boy_CharacterSelect.prefab
  Assets/BossRoom/Prefabs/CharGFX/CharacterGraphics/CharacterSelect/PlayerGraphics_Mage_Girl_CharacterSelect.prefab
  Assets/BossRoom/Prefabs/CharGFX/CharacterGraphics/CharacterSelect/PlayerGraphics_Rogue_Boy_CharacterSelect.prefab
  Assets/BossRoom/Prefabs/CharGFX/CharacterGraphics/CharacterSelect/PlayerGraphics_Rogue_Girl_CharacterSelect.prefab
  Assets/BossRoom/Prefabs/CharGFX/CharacterGraphics/CharacterSelect/PlayerGraphics_Tank_Boy_CharacterSelect.prefab
  Assets/BossRoom/Prefabs/CharGFX/CharacterGraphics/CharacterSelect/PlayerGraphics_Tank_Girl_CharacterSelect.prefab
  Assets/BossRoom/Prefabs/CharGFX/ImpGraphics.prefab
  Assets/BossRoom/Prefabs/CharGFX/PlayerGraphics.prefab
  Assets/BossRoom/Prefabs/Character/Character.prefab
  Assets/BossRoom/Prefabs/Character/Imp.prefab
  Assets/BossRoom/Prefabs/Character/ImpBoss.prefab
  Assets/BossRoom/Prefabs/Character/PlayerAvatar.prefab
  Assets/BossRoom/Prefabs/Shadow.prefab
  Assets/BossRoom/Prefabs/Shadow.prefab.meta
  Assets/BossRoom/Scenes/BossRoom/Lightmap-2_comp_light.exr.meta
  Assets/BossRoom/Scenes/BossRoom/Lightmap-3_comp_light.exr.meta
  Assets/BossRoom/Scripts/Client/AnimationCallbacks/AnimatorFootstepSounds.cs
  Assets/BossRoom/Scripts/Client/AnimationCallbacks/AnimatorTriggeredSpecialFX.cs
  Assets/BossRoom/Scripts/Client/Game/Character/CharacterSwap.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
Labels: Good to Merge

#418 fix: removing room name textbox for ip based connections
  Assets/BossRoom/Scripts/Client/UI/RoomNameBox.cs
Labels: Easy, Good to Merge

#422 fix: Update IET package version to 2.1.1
  Packages/manifest.json
  Packages/packages-lock.json
Labels: Easy, Good to Merge

#361 Feature/session manager
  Assets/BossRoom/Prefabs/GameNetPortal.prefab
  Assets/BossRoom/Prefabs/SessionManager.prefab
  Assets/BossRoom/Prefabs/SessionManager.prefab.meta
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Server/Game/Character/PlayerServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerPostGameState.cs
  Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs
  Assets/BossRoom/Scripts/Shared/Game/Entity/PersistentPlayer.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/SessionManager.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/SessionManager.cs.meta
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/SessionPlayerData.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/SessionPlayerData.cs.meta
Labels: One More Review
