Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2021-04, with the labels that each got.

#245 project name update
  Assets/Readme.asset
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/LICENSE.md
  Packages/com.unity.multiplayer.samples.coop/README.md
  ProjectSettings/ProjectSettings.asset
Labels: Easy, Good to Merge, URGENT

#258 adding initial codeowners file (sam as global)
  .github/CODEOWNERS
Labels: Needs Review

#233 docs: Changelog and Third Party for 0.1.0
  CONTRIBUTING.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Third Party Notices.md
Labels: Easy, URGENT

#254 Architecture.md improvements
  ARCHITECTURE.md
Labels: Needs Review, URGENT

#262 Create third-party contributions file
  third-party contributors.md
Labels: URGENT

#263 Refactor for stealth state, should use bool, not byte
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
  Assets/BossRoom/Scripts/Server/Game/Action/StealthModeAction.cs
  Assets/BossRoom/Scripts/Server/Game/Character/AIBrain.cs
  Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs
Labels: Easy, Good to Merge, URGENT

#175 Feature/animation anticipation
  Assets/BossRoom/GameData/Action/Imp/ImpBaseAttack.asset
  Assets/BossRoom/Models/CharacterSetController_Tank.overrideController
  Assets/BossRoom/Scripts/Client/Game/Action/ActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/ActionVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Action/AnimationOnlyActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/AoeActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/ChargedActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/MeleeActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/StealthModeActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/TargetActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/TrampleActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs
Labels: Reviewed with Comments

#185 Feature/parenting for animation-triggered FX
  Assets/BossRoom/Scripts/Client/AnimationCallbacks/AnimatorTriggeredSpecialFX.cs
Labels: Easy, Good to Merge

#206 [GOMPS-330] Pillars do not stun the boss
  Assets/BossRoom/GameData/Action/Boss/BossImpTrampleAttack.asset
  Assets/BossRoom/GameData/Character/ImpBoss/BaseHP.asset
  Assets/BossRoom/Models/Animation Controllers/CharacterSetController.controller
  Assets/BossRoom/Prefabs/Game/BreakablePillar.prefab
  Assets/BossRoom/Prefabs/GameDataSource.prefab
  Assets/BossRoom/Scripts/Server/Game/Action/TrampleAction.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/IDamageable.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerBreakableLogic.cs
Labels: Good to Merge

#223 [GOMPS-417][GOMPS-379] mage-bolt improvements
  Assets/BossRoom/GameData/Action/Mage/MageBaseAttack.asset
  Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/FXProjectile.cs
  Assets/BossRoom/Scripts/Server/Game/Action/ActionPlayer.cs
  Assets/BossRoom/Scripts/Server/Game/Action/FXProjectileTargetedAction.cs
  Assets/BossRoom/Scripts/Shared/Data/ActionDescription.cs
  Assets/BossRoom/Scripts/Shared/Game/Action/ActionUtils.cs
  Assets/BossRoom/VFX/Prefabs/Caster/fx_magebolt.prefab
Labels: Good to Merge

#252 Feature/rogue sneak visuals improvement [GOMPS-369]
  Assets/BossRoom/GameData/Action/Rogue/RogueStealthMode.asset
  Assets/BossRoom/Prefabs/CharGFX/PlayerGraphics.prefab
  Assets/BossRoom/Scripts/Client/Game/Character/CharacterSwap.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
  Assets/BossRoom/VFX/Materials/FX_M_Charater_Sneaky_Other.mat
  Assets/BossRoom/VFX/Materials/FX_M_Charater_Sneaky_Other.mat.meta
  Assets/BossRoom/VFX/Prefabs/Rogue/StealthModeFX_needupdate.prefab
Labels: Good to Merge

#261 Bug fix: volume controller problems
  Assets/BossRoom/Scripts/Client/UI/StartupUI.cs
Labels: Easy, Good to Merge

#266 Feature/remove unused work-around function (trivial)
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
Labels: Easy, Good to Merge

#246 [GOMPS-355] Bugfix/multiple sessions fail
  Assets/BossRoom/Scripts/Client/Net/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Client/UI/PostGameUI.cs
  Assets/BossRoom/Scripts/Server/Net/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/GameNetPortal.cs
Labels: Good to Merge

#270 Feature/Fix anticipation for mage-bolts through walls
  Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs
Labels: One More Review

#272 (Cleanup) Isolate testing commands
  Assets/BossRoom/Prefabs/State/BossRoomState.prefab
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
  Assets/BossRoom/Scripts/Server/ServerTestingHotkeys.cs
  Assets/BossRoom/Scripts/Server/ServerTestingHotkeys.cs.meta
Labels: Easy, One More Review

#279 Feature/master changes
  .gitattributes
  .github/CODEOWNERS
  ARCHITECTURE.md
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
  Assets/BossRoom/Scripts/Server/Game/Action/StealthModeAction.cs
  Assets/BossRoom/Scripts/Server/Game/Character/AIBrain.cs
  Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs
  Assets/Readme.asset
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/LICENSE.md
  Packages/com.unity.multiplayer.samples.coop/README.md
  Packages/com.unity.multiplayer.samples.coop/Third Party Notices.md
  ProjectSettings/ProjectSettings.asset
  README.md
  third-party contributors.md
Labels: Needs Review

#281 fix multiplayer crash with 3+ players
  Assets/BossRoom/Prefabs/UI/PartyHUD.prefab
Labels: Easy, One More Review

#283 removing duplicate prefabs from main menu scene
  Assets/BossRoom/Scenes/MainMenu.unity
Labels: Easy, One More Review

#274 reverting Jeff's temporary update to S_SimpleDissolve.
  Assets/BossRoom/VFX/Materials/FX_M_GroundCrack.mat
  Assets/BossRoom/VFX/Materials/FX_M_GroundCrack_2.mat
  Assets/BossRoom/VFX/Materials/FX_M_StylizeSmoke.mat
  Assets/BossRoom/VFX/Materials/FX_M_Stylize_Smoke_falldown.mat
  Assets/BossRoom/VFX/Materials/FX_MaskedPanner.mat
  Assets/BossRoom/VFX/Materials/M_MotionFlash.mat
  Assets/BossRoom/VFX/Meshes/Ms_HalfSphere.FBX
  Assets/BossRoom/VFX/Prefabs/Boss/FX_Boss_Charge_Motion.prefab
  Assets/BossRoom/VFX/Prefabs/Environment/FX_Torch_Fire.prefab
  Assets/BossRoom/VFX/Prefabs/Rogue/FX_RogueSkill2_loop.prefab
  Assets/BossRoom/VFX/Shaders/S_SimpleDissolve.shader
  Assets/BossRoom/VFX/Shaders/S_SimpleDissolve.shader.meta
Labels: One More Review

#271 (Cleanup) (feedback needed) Remove redundant list of ServerCharacters
  Assets/BossRoom/Prefabs/Character/Player.prefab
  Assets/BossRoom/Scripts/Server/Game/AIState/IdleAIState.cs
  Assets/BossRoom/Scripts/Server/Game/Character/PlayerServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/Character/PlayerServerCharacter.cs.meta
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerWaveSpawner.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
Labels: Easy, Reviewed with Comments

#289 minor changes to postgame to remove unused popup ui and gamehub
  Assets/BossRoom/Scenes/PostGame.unity
Labels: Good to Merge

#286 Feature/Imp health bars
  Assets/BossRoom/Prefabs/Character/Imp.prefab
  Assets/BossRoom/Scripts/Shared/Game/UI/UIHealth.cs
Labels: Easy, One More Review

#291 Bugfix: testing commands created monsters that were not destroyed on new scene
  Assets/BossRoom/Scripts/Server/ServerTestingHotkeys.cs
Labels: Easy, Good to Merge

#288 Bugfix/host quit strands some players
  Assets/BossRoom/Prefabs/State/MainMenuState.prefab
  Assets/BossRoom/Prefabs/State/MainMenuState.prefab.meta
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/Game/State/ClientPostGameState.cs
  Assets/BossRoom/Scripts/Client/Net/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Client/Net/DisconnectReason.cs
  Assets/BossRoom/Scripts/Client/Net/DisconnectReason.cs.meta
  Assets/BossRoom/Scripts/Client/UI/MainMenuUI.cs
  Packages/com.unity.multiplayer.samples.coop/Third Party Notices.md.meta
Labels: Good to Merge

#295 Feature/Spawner Improvements
  Assets/BossRoom/Prefabs/Game/EnemySpawner.prefab
  Assets/BossRoom/Scripts/Server/Game/AIState/IdleAIState.cs
  Assets/BossRoom/Scripts/Server/Game/Character/AIBrain.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerWaveSpawner.cs
Labels: Good to Merge

#293 Bugfix/broken pieces should not be hit by attacks/projectiles [GOMPS-461]
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/crystal/DestroyedCrystal.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar2_break_parent.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pots/env_pot_break_parent.prefab
  ProjectSettings/TagManager.asset
Labels: Easy, Good to Merge

#296 Feature/Show full particle on imp death
  Assets/BossRoom/Prefabs/CharGFX/ImpGraphics.prefab
  Assets/BossRoom/Scripts/Client/AnimationCallbacks/AnimatorTriggeredSpecialFX.cs
Labels: Easy, Good to Merge

#297 Bugfix: archer charged shot can be spammed
  Assets/BossRoom/GameData/Action/Archer/ArcherChargedShot.asset
Labels: Easy, Good to Merge

#287 [GOMPS-451] Bugfix/cleanup unneeded coroutines
  Assets/BossRoom/Prefabs/State/PostGameState.prefab
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerPostGameState.cs
Labels: Easy, Good to Merge

#302 fixing NRE in RoomNameBox
  Assets/BossRoom/Scripts/Client/UI/RoomNameBox.cs
Labels: Good to Merge

#301 enhancing NetworkStats to also have the host/player type (GOMPS-351)
  Assets/BossRoom/Scripts/Shared/Net/NetworkStats.cs
Labels: Good to Merge

#304 docs: License UCL update and changelog additions
  LICENSE.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/LICENSE.md
Labels: Good to Merge

#307 fixing issue where host disconnects on player leaving.
  Assets/BossRoom/Scripts/Client/Net/ClientGameNetPortal.cs
Labels: Easy, Good to Merge, type:bug

#305 Addresses Help and UI fixes from GOMPS-362
  Assets/BossRoom/Prefabs/UI/PopupPanel.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scripts/Client/UI/MainMenuUI.cs
  Assets/BossRoom/Textures/UI/ui_dropdown_arrow.png
  Assets/BossRoom/Textures/UI/ui_dropdown_arrow.png.meta
  Assets/BossRoom/Textures/UI/ui_help_attack.png
Labels: Easy, Good to Merge

#269 Feature/animation speed cleanup [GOMPS-86]
  Assets/BossRoom/GameData/Character/Archer.asset
  Assets/BossRoom/GameData/Character/Imp.asset
  Assets/BossRoom/GameData/Character/ImpBoss.asset
  Assets/BossRoom/GameData/Character/Mage.asset
  Assets/BossRoom/GameData/Character/Rogue.asset
  Assets/BossRoom/GameData/Character/Tank.asset
  Assets/BossRoom/GameData/Shared.meta
  Assets/BossRoom/GameData/Shared/SharedVisualizationConfiguration.asset
  Assets/BossRoom/GameData/Shared/SharedVisualizationConfiguration.asset.meta
  Assets/BossRoom/Models/Animation Controllers/CharacterSetController.controller
  Assets/BossRoom/Prefabs/CharGFX/BossGraphics.prefab
  Assets/BossRoom/Prefabs/CharGFX/ImpGraphics.prefab
  Assets/BossRoom/Prefabs/CharGFX/PlayerGraphics.prefab
  Assets/BossRoom/Scripts/Client/AnimationCallbacks/AnimatorFootstepSounds.cs
  Assets/BossRoom/Scripts/Client/Game/Action/ActionVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Action/TargetActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs
  Assets/BossRoom/Scripts/Shared/Data/CharacterClass.cs
  Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs
  Assets/BossRoom/Scripts/Shared/ScriptableObjects/VisualizationConfiguration.cs
  Assets/BossRoom/Scripts/Shared/ScriptableObjects/VisualizationConfiguration.cs.meta
Labels: Good to Merge

#273 Bugfix: Add move-check timeout to untargeted Actions [GOMPS-467]
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Server/Game/Action/ActionPlayer.cs
  Assets/BossRoom/Scripts/Server/Game/Action/StealthModeAction.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Shared/Data/ActionDescription.cs
Labels: Good to Merge

#303 Feature/charselect improvements
  Assets/BossRoom/Models/Animation Controllers/UI_LobbyBox.controller
  Assets/BossRoom/Prefabs/UI/PlayerSeatTemplate.prefab
  Assets/BossRoom/Scenes/CharSelect.unity
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientCharSelectState.cs
  Assets/BossRoom/Scripts/Client/UI/UICharSelectClassInfoBox.cs
  Assets/BossRoom/Scripts/Client/UI/UICharSelectPlayerSeat.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
  Assets/BossRoom/Scripts/Server/Net/ServerGameNetPortal.cs
Labels: Good to Merge, One More Review

#284 [GOMPS-471] adding in event unregistration everywhere it was omitted
  Assets/BossRoom/Scripts/Client/Audio/BossMusicStarter.cs
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientProjectileVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientSpawnerVisualization.cs
  Assets/BossRoom/Scripts/Client/Net/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Client/UI/PartyHUD.cs
  Assets/BossRoom/Scripts/Client/UI/PostGameUI.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
  Assets/BossRoom/Scripts/Server/Net/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Game/UI/UIName.cs
  Assets/BossRoom/Scripts/Shared/Net/GameNetPortal.cs
Labels: Reviewed with Comments

#285 Feature/Action Bar Improvements
  Assets/BossRoom/GameData/Action/General/Revive.asset
  Assets/BossRoom/Prefabs/BossRoomHudCanvas.prefab
  Assets/BossRoom/Prefabs/BossRoomHudCanvas.prefab.meta
  Assets/BossRoom/Prefabs/UI/Hero Action Bar.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scripts/Client/UI/HeroActionBar.cs
  Assets/BossRoom/Scripts/Client/UI/UIHUDButton.cs
  Assets/BossRoom/Scripts/Client/UI/UITooltipPopup.cs
  Assets/BossRoom/Textures/UI/ui_revive.png.meta
Labels: One More Review

#294 Bugfix: Fix mage-bolt friendly fire [GOMPS-299]
  Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Server/Game/Action/FXProjectileTargetedAction.cs
Labels: One More Review, Reviewed with Comments

#308 Feature/Shield-Charge attack has anticipation anim [GOMPS-472]
  Assets/BossRoom/Scripts/Client/Game/Action/AoeActionInput.cs
  Assets/BossRoom/Scripts/Client/Game/Action/ChargedActionInput.cs
  Assets/BossRoom/Scripts/Client/Game/Action/ChargedShieldActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Shared/Game/Action/BaseActionInput.cs
Labels: Good to Merge

#310 Fix occasional NREs during object destruction [GOMPS-502][GOMPS-503]
  Assets/BossRoom/Scripts/Shared/Game/UI/UIStateDisplayHandler.cs
Labels: Easy, One More Review

#309 Feature/remove cooldown time variable
  Assets/BossRoom/GameData/Action/Boss/BossImpTrampleAttack.asset
  Assets/BossRoom/Models/Animation Controllers/CharacterSetController.controller
  Assets/BossRoom/Scripts/Client/Game/Action/TrampleActionFX.cs
  Assets/BossRoom/Scripts/Server/Game/AIState/AttackAIState.cs
  Assets/BossRoom/Scripts/Server/Game/Action/Action.cs
  Assets/BossRoom/Scripts/Server/Game/Action/ActionPlayer.cs
  Assets/BossRoom/Scripts/Server/Game/Action/TrampleAction.cs
  Assets/BossRoom/Scripts/Shared/Data/ActionDescription.cs
Labels: One More Review

#312 Feature/another null-check to fix NRE in editor shutdown
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
Labels: Easy

#311 Feature/Anticipation logic tweaks [GOMPS-505]
  Assets/BossRoom/Scripts/Client/Game/Action/ActionVisualization.cs
Labels: Easy, Good to Merge

#280 Feature/Rogue Dash Attack
  Assets/BossRoom/GameData/Action/Rogue/RogueDashAttack.asset
  Assets/BossRoom/GameData/Action/Rogue/RogueDashAttack.asset.meta
  Assets/BossRoom/GameData/Character/Rogue.asset
  Assets/BossRoom/Models/Animation Controllers/CharacterSetController.controller
  Assets/BossRoom/Prefabs/CharGFX/PlayerGraphics.prefab
  Assets/BossRoom/Prefabs/GameDataSource.prefab
  Assets/BossRoom/Scripts/Client/Game/Action/ActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/DashAttackActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/DashAttackActionFX.cs.meta
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Server/Game/Action/Action.cs
  Assets/BossRoom/Scripts/Server/Game/Action/ActionPlayer.cs
  Assets/BossRoom/Scripts/Server/Game/Action/DashAttackAction.cs
  Assets/BossRoom/Scripts/Server/Game/Action/DashAttackAction.cs.meta
  Assets/BossRoom/Scripts/Server/Game/Action/MeleeAction.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/IDamageable.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerBreakableLogic.cs
  Assets/BossRoom/Scripts/Shared/Game/Action/ActionRequestData.cs
  Assets/BossRoom/Scripts/Shared/Game/Action/ActionUtils.cs
  Assets/BossRoom/VFX/Prefabs/Rogue/FX_RogueSkill2_Start.prefab
  Assets/BossRoom/VFX/Prefabs/Rogue/FX_RogueSkill2_end.prefab
  Assets/BossRoom/VFX/Prefabs/Rogue/FX_RogueSkill2_loop.prefab
Labels: Good to Merge

#292 Feature/static scene network objects
  Assets/BossRoom/GameData/GameEvents.meta
  Assets/BossRoom/GameData/GameEvents/BossDefeated.asset
  Assets/BossRoom/GameData/GameEvents/BossDefeated.asset.meta
  Assets/BossRoom/GameData/RuntimeNetworkObjectsParent.asset
  Assets/BossRoom/GameData/RuntimeNetworkObjectsParent.asset.meta
  Assets/BossRoom/GameData/RuntimeObjectsParent.asset
  Assets/BossRoom/GameData/RuntimeObjectsParent.asset.meta
  Assets/BossRoom/Prefabs/CharGFX/BossGraphics.prefab
  Assets/BossRoom/Prefabs/CharGFX/ImpGraphics.prefab
  Assets/BossRoom/Prefabs/CharGFX/PlayerGraphics.prefab
  Assets/BossRoom/Prefabs/Character/Character.prefab
  Assets/BossRoom/Prefabs/Character/ImpBoss.prefab
  Assets/BossRoom/Prefabs/Dungeon/AllImpsInDungeon.prefab
  Assets/BossRoom/Prefabs/Dungeon/AllPillarsDungeon.prefab
  Assets/BossRoom/Prefabs/Dungeon/AllPotsinDungeon.prefab
  Assets/BossRoom/Prefabs/Dungeon/AllSpawnersInDungeon.prefab
  Assets/BossRoom/Prefabs/Game/ImpNetSpawner.prefab
  Assets/BossRoom/Prefabs/Game/RuntimeNetworkObjects.prefab
  Assets/BossRoom/Prefabs/Game/RuntimeNetworkObjects.prefab.meta
  Assets/BossRoom/Prefabs/Game/RuntimeObjects.prefab
  Assets/BossRoom/Prefabs/Game/RuntimeObjects.prefab.meta
  Assets/BossRoom/Prefabs/Game/StaticNetworkObjects.prefab
  Assets/BossRoom/Prefabs/Game/StaticNetworkObjects.prefab.meta
  Assets/BossRoom/Prefabs/NetworkingManager.prefab
  Assets/BossRoom/Prefabs/State/BossRoomState.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scripts/Client/Audio/BossMusicStarter.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Client/UI/HeroActionBar.cs
  Assets/BossRoom/Scripts/Editor/BossRoom.Editor.asmdef
  Assets/BossRoom/Scripts/Editor/GameEventEditor.cs
  Assets/BossRoom/Scripts/Editor/GameEventEditor.cs.meta
  Assets/BossRoom/Scripts/Server/Game/Action/ReviveAction.cs
  Assets/BossRoom/Scripts/Server/Game/Character/AIBrain.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/RaiseEventOnLifeChange.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/RaiseEventOnLifeChange.cs.meta
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerWaveSpawner.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
  Assets/BossRoom/Scripts/Server/Net/NetSpawnPoint.cs
  Assets/BossRoom/Scripts/Shared/Data/TransformRegister.cs
  Assets/BossRoom/Scripts/Shared/Data/TransformRegister.cs.meta
  Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs
  Assets/BossRoom/Scripts/Shared/NetworkLifeState.cs
  Assets/BossRoom/Scripts/Shared/NetworkLifeState.cs.meta
  Assets/BossRoom/Scripts/Shared/ScriptableObjects/GameEvent.cs
  Assets/BossRoom/Scripts/Shared/ScriptableObjects/GameEvent.cs.meta
  Assets/BossRoom/Scripts/Shared/ScriptableObjects/IGameEventListenable.cs
  Assets/BossRoom/Scripts/Shared/ScriptableObjects/IGameEventListenable.cs.meta
  Assets/BossRoom/Scripts/Shared/ScriptableObjects/TransformVariable.cs
  Assets/BossRoom/Scripts/Shared/ScriptableObjects/TransformVariable.cs.meta
  Assets/BossRoom/Scripts/Shared/ScriptableObjects/UnityEventGameEventListener.cs
  Assets/BossRoom/Scripts/Shared/ScriptableObjects/UnityEventGameEventListener.cs.meta
Labels: One More Review

#315 hotfix for a compilation issue
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
Labels: Easy

#298 sanitized text in input/IP & port fields on input change callback
  Assets/BossRoom/Prefabs/UI/PopupPanel.prefab
  Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs
Labels: Needs Review

#306 updating shader variants
  Assets/BossRoom/VFX/Shaders/Prewarming.shadervariants
Labels: Good to Merge

#317 Fix boss-death helmet jiggle by deparenting helmet [GOMPS-463]
  Assets/BossRoom/Models/CharacterSet.fbx.meta
  Assets/BossRoom/Prefabs/CharGFX/BossGraphics.prefab
  Assets/BossRoom/Scripts/Client/AnimationCallbacks/BossDeathHelmetHandler.cs
  Assets/BossRoom/Scripts/Client/AnimationCallbacks/BossDeathHelmetHandler.cs.meta
Labels: Good to Merge

#318 Feature/optimization integration
  Assets/BossRoom/Material/Characters/Enemy_Eyes_sheet.mat
  Assets/BossRoom/Material/Characters/Hero_Eyes_sheet.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Archer_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Archer_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Mage_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Mage_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Rogue_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Rogue_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Tank_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Tank_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Archer_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Archer_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Boss.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Imp.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Mage_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Mage_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Rogue_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Rogue_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Tank_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Tank_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Archer.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Boss.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Imp.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Mage_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Mage_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Rogue.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Tank.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Archer.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Imp.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Mage.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Rogue.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Tank.mat
  Assets/BossRoom/Material/Dungeon/env_deco.mat
  Assets/BossRoom/PostProcessing/PostProcessVolume Profile.asset
  Assets/BossRoom/Prefabs/CharGFX/BossGraphics.prefab
  Assets/BossRoom/Prefabs/CharGFX/ImpGraphics.prefab
  Assets/BossRoom/Prefabs/GameCam/Main Camera.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/VFX/Materials/FX_M_Flame.mat
  Assets/BossRoom/VFX/Materials/FX_M_TorchFire.mat
  Assets/BossRoom/VFX/Meshes/Materials/FX_M_Glow_01.mat
  Assets/BossRoom/VFX/Prefabs/Environment/FX_Torch_Fire.prefab
  ProjectSettings/ProjectSettings.asset
Labels: One More Review
