Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2021-12, with the labels that each got.

#424 fix: inititalize host session data while using URelay or Photon
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Labels: URGENT, Easy, One More Review

#419 fix: removing workaround for ngo issue 745
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
Labels: Easy, One More Review

#417 fix: re-enabling positional smoothing on graphics GameObject
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientProjectileVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Utils/VisualUtils.cs
  Assets/BossRoom/Scripts/Client/UI/UIStateDisplayHandler.cs
Labels: Needs Review
