Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2021-05, with the labels that each got.

#321 Adjustments for balance and difficulty scaling with more players
  Assets/BossRoom/GameData/Action/Archer/ArcherBaseAttack.asset
  Assets/BossRoom/GameData/Action/Boss/BossImpBaseAttack.asset
  Assets/BossRoom/GameData/Action/Imp/ImpBaseAttack.asset
  Assets/BossRoom/GameData/Action/Mage/MageHeal.asset
  Assets/BossRoom/GameData/Action/Rogue/RogueBaseAttack.asset
  Assets/BossRoom/GameData/Action/Rogue/RogueDashAttack.asset
  Assets/BossRoom/GameData/Action/Tank/TankBaseAttack.asset
  Assets/BossRoom/GameData/Character/Archer/BaseHP.asset
  Assets/BossRoom/GameData/Character/Imp/BaseHP.asset
  Assets/BossRoom/GameData/Character/ImpBoss/BaseHP.asset
  Assets/BossRoom/GameData/Character/Rogue/BaseHP.asset
  Assets/BossRoom/GameData/Character/Tank/BaseHP.asset
  Assets/BossRoom/Prefabs/Dungeon/Dungeon.prefab
  Assets/BossRoom/Prefabs/Game/StaticNetworkObjects.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scripts/Client/Game/Action/MeleeActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/TargetActionFX.cs
Labels: One More Review

#319 Minor gameplay polish tasks
  Assets/BossRoom/Prefabs/BossRoomHudCanvas.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/crystal/DestroyedCrystal.prefab
  Assets/BossRoom/Prefabs/UI/Hero Action Bar.prefab
  Assets/BossRoom/Prefabs/UI/Hero Emote Bar.prefab
  Assets/BossRoom/Scripts/Client/Game/Action/AoeActionInput.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Server/Game/Action/MeleeAction.cs
  Assets/BossRoom/VFX/Materials/FX_Crystal_Broken.mat
  Assets/BossRoom/VFX/Materials/FX_Crystal_Broken.mat.meta
Labels: One More Review

#322 updating project to Unity LTS 2020.3.6f1
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
Labels: Easy

#320 [GOMPS-470] cleaning up todos and fixmes
  Assets/BossRoom/Prefabs/Game/BreakablePot.prefab
  Assets/BossRoom/Prefabs/Game/PrebrokenPot.prefab
  Assets/BossRoom/Prefabs/Game/PrebrokenPot.prefab.meta
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientBreakableVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientSpawnerVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientSpawnerVisualization.cs.meta
  Assets/BossRoom/Scripts/Client/Game/State/ClientPostGameState.cs
  Assets/BossRoom/Scripts/Client/Net/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Client/Net/DisconnectReason.cs
  Assets/BossRoom/Scripts/Client/UI/MainMenuUI.cs
  Assets/BossRoom/Scripts/Server/Game/Action/MeleeAction.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
  Assets/BossRoom/Scripts/Server/Net/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/GameNetPortal.cs
  Assets/BossRoom/VFX/Shaders/Prewarming.shadervariants
Labels: One More Review

#323 [GOMPS-228][GOMPS-513] fixing handful of remaining bugs
  Assets/BossRoom/Scripts/Client/Game/Action/ChargedLaunchProjectileActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerWaveSpawner.cs
  Assets/BossRoom/Scripts/Shared/Game/Action/ActionRequestData.cs
Labels: One More Review

#326 [GOMPS-522] fixes character jitter in high packet loss scenarios
  Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs
Labels: One More Review

#325 Bugfix/gomps 521 fixes ArgumentNullException
  Assets/BossRoom/Prefabs/UI/PartyHUD.prefab
Labels: Easy, One More Review

#328 Bugfix/gomps 527 pots not breaking on client
  Assets/BossRoom/Prefabs/NetworkingManager.prefab
Labels: Good to Merge

#327 Bugfix: boss's "charging" particles not canceled when stunned
  Assets/BossRoom/Prefabs/CharGFX/BossGraphics.prefab
Labels: Easy, Good to Merge

#331 [GOMPS-532] removing incorrect use of null propagation on Unity object
  Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs
Labels: One More Review

#329 [GOMPS-524] fixing issue where you wade through the treasure chest dais
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/animated/env_treasure_chest_ani.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_boss_floor_2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scenes/BossRoom/NavMesh-Patch1.asset
  Assets/BossRoom/Scripts/Client/ClickFeedback.cs
Labels: One More Review

#324 displaying better initial text for CharSelect scene
  Assets/BossRoom/Prefabs/Game/StaticNetworkObjects.prefab
  Assets/BossRoom/Prefabs/UI/BossRoomHudCanvas.prefab
  Assets/BossRoom/Prefabs/UI/BossRoomHudCanvas.prefab.meta
  Assets/BossRoom/Prefabs/UI/CharacterSelectCanvas.prefab
  Assets/BossRoom/Prefabs/UI/CharacterSelectCanvas.prefab.meta
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scenes/CharSelect.unity
Labels: Easy, Needs Review

#333 upgrading to 2020.3.8f1 LTS
  ProjectSettings/ProjectVersion.txt
Labels: Easy, Needs Review

#330 Uploading pull-request-template
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: Easy

#336 fetching MLAPI experimental package through registry
  Packages/manifest.json
  Packages/packages-lock.json
Labels: Easy, Needs Review

#335 removed shadow casting on most dungeon prefabs, dynamic batching enabled, instancing on most dungeon prefabs
  Assets/BossRoom/Material/Characters/Enemy_Mouth_sheet.mat
  Assets/BossRoom/Material/Characters/Hero_Mouth_sheet.mat
  Assets/BossRoom/Material/Dungeon/env_deco_dark.mat
  Assets/BossRoom/Material/Dungeon/lava.mat
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/animated/env_door_boss_ani.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/animated/env_door_gears_ani.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/animated/env_floor_switch_glow.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/animated/env_floor_switch_interactive.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/animated/env_treasure_chest_ani.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/crystal/DestroyedCrystal.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_Door.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_banner.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_barrier.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_boss_floor.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_boss_floor_2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_door_boss_head.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor3.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor_barrier_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor_grate.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_lava.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_pebbles.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_rock.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_roots.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_spawn_door.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_spiderweb_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_torch2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_corner_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_diagonal_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_diagonal_2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_diagonal_3.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_straight_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_straight_2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_straight_3.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_straight_cap_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_corner_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_diagonal_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_diagonal_2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_diagonal_3.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_straight_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_straight_2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_straight_3.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_straight_cap_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar2_break_parent.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pots/env_pot.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pots/env_pot_break_parent.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pots/env_pot_heavy.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon.prefab
  Assets/BossRoom/Prefabs/Game/BreakableCrystal.prefab
  Assets/BossRoom/Prefabs/InteractiveFloorSwitch.prefab
  Assets/BossRoom/Scripts/Client/Effects/ScrollingUVs.cs
  Assets/BossRoom/VFX/Materials/FX_Crystal.mat
  Assets/BossRoom/VFX/Materials/FX_Crystal_Broken.mat
  ProjectSettings/ProjectSettings.asset
Labels: Needs Review

#343 Fixing parameter exception when connecting to lobby
  Packages/manifest.json
  Packages/packages-lock.json
Labels: Easy, URGENT
