Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2022-03, with the labels that each got.

#498 cherrypick fix: same player number for multiple players in second playthrough
  Assets/BossRoom/Scripts/Client/Game/State/ClientCharSelectState.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
  Assets/BossRoom/Scripts/Shared/Game/State/CharSelectData.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/SessionPlayerData.cs
Labels: 2-Easy, 1-Needs Review

#496 fix: fixing send queue error
  Assets/BossRoom/Prefabs/NetworkingManager.prefab
Labels: 1-Needs Review, 0-GDC-cherrypick

#485 feat: use DTLS for relay
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/UnityRelayUtilities.cs
Labels: 2-One More Review

#504 hack: hard code relay region
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Labels: 4-On Hold, 2-Easy, 3-Good to Merge, 0-workaround

#494 feat: popup panel for connection status messages
  Assets/BossRoom/Prefabs/UI/SettingsPanelCanvas.prefab
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/ConnectionStatusMessageUIManager.cs
  Assets/BossRoom/Scripts/Client/UI/ConnectionStatusMessageUIManager.cs.meta
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs
  Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs.meta
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
Labels: 0-URGENT, 3-Good to Merge, 0-GDC-cherrypick

#447 feat: kill enemies cheat
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
Labels: 2-Easy, 3-Good to Merge

#448 feat: heal player cheat
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
Labels: 2-Easy, 3-Good to Merge

#451 feat: toggle door cheat
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
  Assets/BossRoom/Scripts/Server/ServerSwitchedDoor.cs
Labels: 2-Easy, 2-One More Review

#449 feat: speedhack toggle cheat
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs
Labels: 2-Easy, 2-One More Review

#452 feat: portals toggle cheat
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerEnemyPortal.cs
Labels: 2-Easy, 2-One More Review

#506 feat: popup panel for connection status messages (#494)
  Assets/BossRoom/Prefabs/UI/SettingsPanelCanvas.prefab
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/ConnectionStatusMessageUIManager.cs
  Assets/BossRoom/Scripts/Client/UI/ConnectionStatusMessageUIManager.cs.meta
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs
  Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs.meta
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
Labels: 0-URGENT, 1-Needs Review

#450 feat: teleport mode cheat
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs
Labels: 2-Easy, 3-Good to Merge

#502 feat: IP connection window inside main menu
  Assets/BossRoom/Prefabs/UI/IPPopup.prefab
  Assets/BossRoom/Prefabs/UI/IPPopup.prefab.meta
  Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/IPHostingUI.cs
  Assets/BossRoom/Scripts/Client/UI/IPHostingUI.cs.meta
  Assets/BossRoom/Scripts/Client/UI/IPJoiningUI.cs
  Assets/BossRoom/Scripts/Client/UI/IPJoiningUI.cs.meta
  Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs.meta
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyCreationUI.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Labels: 3-Good to Merge, 0-GDC-cherrypick

#508 feat: IP connection window inside main menu (#502)
  Assets/BossRoom/Prefabs/UI/IPPopup.prefab
  Assets/BossRoom/Prefabs/UI/IPPopup.prefab.meta
  Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/IPHostingUI.cs
  Assets/BossRoom/Scripts/Client/UI/IPHostingUI.cs.meta
  Assets/BossRoom/Scripts/Client/UI/IPJoiningUI.cs
  Assets/BossRoom/Scripts/Client/UI/IPJoiningUI.cs.meta
  Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs.meta
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyCreationUI.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Labels: 2-Easy, 1-Needs Review

#486 fix: handling of host disconnect
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
Labels: 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#499 fix: username changing before game
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
Labels: 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#512 fix: NetworkAnimator being called on clients
  Assets/BossRoom/Scripts/Server/Game/Character/ServerAnimationHandler.cs
Labels: 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#473 Feature/UI camera prefab
  Assets/BossRoom/Prefabs/GameCam/MenuCamera.prefab
  Assets/BossRoom/Prefabs/GameCam/MenuCamera.prefab.meta
  Assets/BossRoom/Scenes/CharSelect.unity
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scenes/PostGame.unity
Labels: 2-Easy, 2-One More Review

#500 hack fix: disabling client side rate limiting for GDC
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Labels: 2-Easy, 3-Good to Merge, 0-workaround

#509 cherrypick fix: Adding handling of host disconnect (#486)
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
Labels: 2-Easy, 2-One More Review

#518 Lobby UI Visual Rework
  Assets/BossRoom/Prefabs/UI/IPPopup.prefab
  Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
Labels: 0-URGENT, 3-Good to Merge, priority:high, 0-GDC-cherrypick

#517 fix: client writing to NetworkVariable inside ServerCharacterMovement
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs
Labels: 2-Easy, 2-Reviewed with Comments, 0-workaround

#507 Simplified Floor Tiles
  Assets/BossRoom/Material/Dungeon/env_deco.mat
  Assets/BossRoom/Models/DungeonPieces.FBX
  Assets/BossRoom/Models/DungeonPieces.FBX.meta
  Assets/BossRoom/Prefabs/Dungeon/BossRoom.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor3.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor4.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor4.prefab.meta
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor5.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor5.prefab.meta
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor6.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor6.prefab.meta
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor7.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor7.prefab.meta
  Assets/BossRoom/Prefabs/Dungeon/Entrance.prefab
  Assets/BossRoom/Prefabs/Dungeon/TransitionArea.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scenes/BossRoom/DungeonBossRoom.unity
  Assets/BossRoom/Scenes/BossRoom/DungeonTransition.unity
  Assets/BossRoom/Scenes/BossRoom/GoodBaking.lighting
  Assets/BossRoom/Scenes/BossRoom/LightingData.asset
  Assets/BossRoom/Scenes/BossRoom/Lightmap-0_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-1_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-2_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-3_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-4_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-5_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-0.png
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-1.png
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-2.png
Labels: 0-URGENT, 1-Needs Review, priority:high, priority:highest, type:feature, 0-GDC-cherrypick

#495 feat: loading screen (GDC version)
  Assets/BossRoom/Prefabs/SceneLoader.prefab
  Assets/BossRoom/Prefabs/SceneLoader.prefab.meta
  Assets/BossRoom/Prefabs/UI/LoadingScreen.prefab
  Assets/BossRoom/Prefabs/UI/LoadingScreen.prefab.meta
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Client/UI/PostGameUI.cs
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
  Assets/BossRoom/Scripts/DebugCheats/com.unity.multiplayer.samples.bossroom.debug.cheats.asmdef
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ClientLoadingScreen.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ClientLoadingScreen.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ServerAdditiveSceneLoader.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ServerAdditiveSceneLoader.cs.meta
Labels: 3-Good to Merge, 0-workaround

#520 Cherrypick: Lobby Visual Rework
  Assets/BossRoom/Prefabs/UI/IPPopup.prefab
  Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
Labels: 0-GDC-cherrypick

#519 Cherrypick: Simplified Floor Tiles
  Assets/BossRoom/Material/Dungeon/env_deco.mat
  Assets/BossRoom/Models/DungeonPieces.FBX
  Assets/BossRoom/Models/DungeonPieces.FBX.meta
  Assets/BossRoom/Prefabs/Dungeon/BossRoom.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor3.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor4.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor4.prefab.meta
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor5.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor5.prefab.meta
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor6.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor6.prefab.meta
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor7.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor7.prefab.meta
  Assets/BossRoom/Prefabs/Dungeon/Entrance.prefab
  Assets/BossRoom/Prefabs/Dungeon/TransitionArea.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scenes/BossRoom/DungeonBossRoom.unity
  Assets/BossRoom/Scenes/BossRoom/DungeonTransition.unity
  Assets/BossRoom/Scenes/BossRoom/GoodBaking.lighting
  Assets/BossRoom/Scenes/BossRoom/LightingData.asset
  Assets/BossRoom/Scenes/BossRoom/Lightmap-0_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-1_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-2_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-3_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-4_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-5_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-0.png
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-1.png
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-2.png
Labels: 0-GDC-cherrypick

#505 lobby fix: Removing quit when lobby detects host left.
  Assets/BossRoom/Scripts/Client/UI/UIQuitPanel.cs
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Labels: 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#511 lobby fix: Adding instructions when we get a service error on conflicting joins
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs.meta
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Auth/AuthenticationServiceFacade.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Infrastructure/Messages/UnityServiceErrorMessage.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyAPIInterface.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Labels: 2-Easy, 1-Needs Review, 0-GDC-cherrypick

#522 fix: populate lobby room name if creation room input field is empty
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
Labels: 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#524 fix: populate lobby room name if creation room input field is empty (#522)
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
Labels: 2-Easy, 1-Needs Review

#527 Fix: Holes in Floor
  Assets/BossRoom/Prefabs/Dungeon/BossRoom.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor6.prefab
  Assets/BossRoom/Prefabs/Dungeon/Entrance.prefab
  Assets/BossRoom/Scenes/BossRoom/LightingData.asset
  Assets/BossRoom/Scenes/BossRoom/Lightmap-0_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-1_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-2_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-3_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-4_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-5_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-0.png
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-1.png
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-2.png
Labels: 0-URGENT, 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#526 Fix: Lobby UI Blue Banner Scaling
  Assets/BossRoom/Prefabs/UI/IPPopup.prefab
  Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Textures/UI/ui_char_select_title2.png
  Assets/BossRoom/Textures/UI/ui_char_select_title2.png.meta
Labels: 2-Easy, 3-Good to Merge, type:bug, 0-GDC-cherrypick

#529 cherrypick fix: NetworkAnimator being called on clients (#512)
  Assets/BossRoom/Scripts/Server/Game/Character/ServerAnimationHandler.cs
Labels: 2-Easy, 1-Needs Review

#530 cherrypick fix: username changing before game (#499)
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
Labels: 2-Easy, 1-Needs Review

#531 cherrypick fix: NREs when trying to quit (#516)
  Assets/BossRoom/Scripts/Shared/Game/UI/Editor/NetworkLatencyWarning.cs
Labels: 2-Easy, 1-Needs Review

#533 Cherrypick: Fill in Floor Holes
  Assets/BossRoom/Prefabs/Dungeon/BossRoom.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor6.prefab
  Assets/BossRoom/Prefabs/Dungeon/Entrance.prefab
  Assets/BossRoom/Scenes/BossRoom/LightingData.asset
  Assets/BossRoom/Scenes/BossRoom/Lightmap-0_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-1_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-2_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-3_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-4_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-5_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-0.png
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-1.png
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-2.png
Labels: 0-GDC-cherrypick

#534 Cherry pick: Lobby blue banner fix
  Assets/BossRoom/Prefabs/UI/IPPopup.prefab
  Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Textures/UI/ui_char_select_title2.png
  Assets/BossRoom/Textures/UI/ui_char_select_title2.png.meta
Labels: 0-GDC-cherrypick

#492 chore: adding project ID leak detect
  .github/workflows/leak_detect.yml
Labels: 2-Easy, 3-Good to Merge

#523 fix: postgame menu button
  Assets/BossRoom/Scripts/Client/UI/PostGameUI.cs
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
Labels: 2-Easy, 3-Good to Merge, 0-workaround

#535 fix: added IP button to main menu
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
Labels: 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#538 fix: IP window button
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
Labels: 2-Easy, 1-Needs Review

#532 fix: not returning to mainmenu when reconnect fails
  Assets/BossRoom/Scripts/Client/UI/ConnectionStatusMessageUIManager.cs
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
Labels: 1-Needs Review, 0-workaround

#539 Fix for clients getting nullref when lobby host disconnects
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
Labels: 2-Easy, 1-Needs Review

#537 fix: simpler quitting flow
  Assets/BossRoom/Scripts/Client/UI/UIQuitPanel.cs
Labels: 2-Easy, 3-Good to Merge, 0-workaround

#536 switching NGO to custom branch for some cherrypicked fixes
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 1-Needs Review, 0-workaround

#541 fix: adjusted layer collision matrix
  ProjectSettings/DynamicsManager.asset
Labels: 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#542 fix: nav mesh floating patches removed
  Assets/BossRoom/Scenes/BossRoom/NavMesh-DungeonNavMesh.asset
Labels: 2-Easy, 1-Needs Review, 0-GDC-cherrypick

#528 feat: Adding transport rtt to UI stats
  Assets/BossRoom/Scripts/Shared/Net/NetworkStats.cs
Labels: 2-Easy, 1-Needs Review, 0-GDC-cherrypick

#546 fix: nav mesh floating patches removed (#542)
  Assets/BossRoom/Scenes/BossRoom/NavMesh-DungeonNavMesh.asset
Labels: 2-Easy, 1-Needs Review

#476 feat: player architecture ARCHITECTURE.md addition
  ARCHITECTURE.md
  Assets/BossRoom/Scripts/Client/com.unity.multiplayer.samples.bossroom.client.asmdef
  Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkAvatarGuidState.cs
  Assets/BossRoom/Scripts/Shared/Game/Entity/PersistentPlayer.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/com.unity.multiplayer.samples.bossroom.shared.asmdef
  Documentation/Photon-Realtime/Images/Boss-Room-Host-Confirm.png
  Documentation/Photon-Realtime/Images/Boss-Room-Host-Dropdown.png
  Documentation/Photon-Realtime/Images/Boss-Room-Join-Dropdown.png
  Documentation/Photon-Realtime/Images/Boss-Room-Join.png
  Documentation/Photon-Realtime/Images/Boss-Room-Lobby-Extra.png
  Documentation/Photon-Realtime/Images/Boss-Room-Lobby.png
  Documentation/Photon-Realtime/Images/Photon-App.png
  Documentation/Photon-Realtime/Images/Photon-Dashboard.png
  Documentation/Photon-Realtime/Readme.md
  README.md
Labels: 2-Easy, 3-Good to Merge

#488 feat: replace guid with auth playerid for session management
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
  Assets/BossRoom/Scripts/Client/com.unity.multiplayer.samples.bossroom.client.asmdef
  Assets/BossRoom/Scripts/Shared/ClientPrefs.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/ProfileManager.cs
  Assets/BossRoom/Scripts/Shared/ProfileManager.cs.meta
  Assets/BossRoom/Scripts/Shared/com.unity.multiplayer.samples.bossroom.shared.asmdef
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs
Labels: 3-Good to Merge, 0-GDC-cherrypick

#548 cherrypick feat: replace guid with auth playerid for session management (#488)
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
  Assets/BossRoom/Scripts/Client/com.unity.multiplayer.samples.bossroom.client.asmdef
  Assets/BossRoom/Scripts/Shared/ClientPrefs.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/ProfileManager.cs
  Assets/BossRoom/Scripts/Shared/ProfileManager.cs.meta
  Assets/BossRoom/Scripts/Shared/com.unity.multiplayer.samples.bossroom.shared.asmdef
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs
Labels: 1-Needs Review, 0-GDC-cherrypick

#547 feat: authentication failure message popups will tell the user to try direct ip connection option
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Auth/AuthenticationServiceFacade.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Infrastructure/Messages/UnityServiceErrorMessage.cs
Labels: 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#515 fix: leaving lobby when disconnecting
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Infrastructure/RateLimitCooldown.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyAPIInterface.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs
Labels: 0-URGENT, 1-Needs Review, 0-GDC-cherrypick

#549 fix: workaround for fixing the loading screen never going away on clients
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
Labels: 0-URGENT, 1-Needs Review, 0-workaround

#553 cherrypick fix: leaving lobby when disconnecting (#515)
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Infrastructure/RateLimitCooldown.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyAPIInterface.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs
Labels: 1-Needs Review, 0-GDC-cherrypick

#552 fix: unready button not clickable on wide screens
  Assets/BossRoom/Models/UI_LobbyBox_LockedIn.anim
  Assets/BossRoom/Prefabs/UI/CharacterSelectCanvas.prefab
  Assets/BossRoom/Prefabs/UI/PlayerSeatTemplate.prefab
Labels: 2-Easy, 2-One More Review, 0-GDC-cherrypick

#551 fix: leaving lobby when connection denied
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Labels: 1-Needs Review, 0-GDC-cherrypick

#557 fix: arrow ClientRpc error
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientProjectileVisualization.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerProjectileLogic.cs
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ArrowGraphics.prefab
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow1Graphics.prefab
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow2Graphics.prefab
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow3Graphics.prefab
Labels: 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#555 Fix: Darker Eyebrows for Player Characters
  Assets/BossRoom/Material/Characters/Hero_Eyes_sheet.mat
Labels: 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#559 fix: RTT text too small
  Assets/BossRoom/Prefabs/Debug Overlay Canvas.prefab
  Assets/BossRoom/Scripts/Shared/Net/NetworkStats.cs
Labels: 2-Easy, 1-Needs Review, 0-GDC-cherrypick

#560 cherrypick fix: arrow not sending a clientrpc when despawned, vfx reset on spawn/despawn
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientProjectileVisualization.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerProjectileLogic.cs
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ArrowGraphics.prefab
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow1Graphics.prefab
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow2Graphics.prefab
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow3Graphics.prefab
Labels: 2-Easy, 1-Needs Review

#561 cherrypick fix: RTT text too small
  Assets/BossRoom/Prefabs/Debug Overlay Canvas.prefab
  Assets/BossRoom/Scripts/Shared/Net/NetworkStats.cs
Labels: 2-Easy, 1-Needs Review

#558 fix: nullref on host when disconnecting
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
Labels: 0-URGENT, 2-Easy, 3-Good to Merge, 0-workaround

#564 Darker Eyebrows for Player Characters (#555)
  Assets/BossRoom/Material/Characters/Hero_Eyes_sheet.mat
Labels: 2-Easy, 0-GDC-cherrypick

#525 feat: display popup when failing to connect to full lobby
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
Labels: 0-URGENT, 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#565 fix: updaterunner item already added
  Assets/BossRoom/Scripts/Shared/Infrastructure/UpdateRunner.cs
Labels: 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#569 Fix: Refactor of click target feedback
  Assets/BossRoom/Models/ClickFeedbackController.controller
  Assets/BossRoom/Models/ClickFeedbackController.controller.meta
  Assets/BossRoom/Models/UI_GroundClick.anim
  Assets/BossRoom/Models/UI_GroundClick.anim.meta
  Assets/BossRoom/Prefabs/Character/PlayerAvatar.prefab
  Assets/BossRoom/Prefabs/Click_Feedback.prefab
  Assets/BossRoom/Scripts/Client/ClientClickFeedback.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClickFeedbackLerper.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClickFeedbackLerper.cs.meta
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/VFX/Materials/GroundClick.mat
  Assets/BossRoom/VFX/Prefabs/UI/fx_GroundClickFX.prefab
Labels: 3-Good to Merge, type:bug, 0-GDC-cherrypick

#568 feat: better lobby exceptions handling
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Labels: 0-URGENT, 2-Easy, 1-Needs Review, 0-workaround

#570 Cherrypick: Refactor of click feedback target
  Assets/BossRoom/Models/ClickFeedbackController.controller
  Assets/BossRoom/Models/ClickFeedbackController.controller.meta
  Assets/BossRoom/Models/UI_GroundClick.anim
  Assets/BossRoom/Models/UI_GroundClick.anim.meta
  Assets/BossRoom/Prefabs/Character/PlayerAvatar.prefab
  Assets/BossRoom/Prefabs/Click_Feedback.prefab
  Assets/BossRoom/Scripts/Client/ClientClickFeedback.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClickFeedbackLerper.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClickFeedbackLerper.cs.meta
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/VFX/Materials/GroundClick.mat
  Assets/BossRoom/VFX/Prefabs/UI/fx_GroundClickFX.prefab
Labels: 0-GDC-cherrypick

#563 fix: null refs preventing users from quitting
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
Labels: 0-URGENT, 2-Easy, 3-Good to Merge, 0-GDC-cherrypick

#571 fix: mage FX graphics not offset
  Assets/BossRoom/Prefabs/CharGFX/PlayerGraphics_Mage.prefab
Labels: 2-Easy, 1-Needs Review, 0-GDC-cherrypick

#562 fix: disconnect issue with wifi turned off
  Assets/BossRoom/Prefabs/NetworkingManager.prefab
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/PostGameUI.cs
  Assets/BossRoom/Scripts/Client/UI/UIQuitPanel.cs
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/UnityRelayUtilities.cs
Labels: 0-URGENT, 1-Needs Review, 0-GDC-cherrypick, 0-workaround

#572 cherrypick fix: null refs when quitting (#563)
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyAPIInterface.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Labels: 2-Easy, 1-Needs Review, 0-GDC-cherrypick

#573 fix: hard coding frame rate
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
Labels: 0-URGENT, 2-Easy, 1-Needs Review, 0-GDC-cherrypick

#575 cherry pick fix: mage FX graphics not offset (#571)
  Assets/BossRoom/Prefabs/CharGFX/PlayerGraphics_Mage.prefab
Labels: 2-Easy, 1-Needs Review

#584 VFX Optimization Pass
  Assets/BossRoom/VFX/Materials/FX_M_Glow_13.mat
  Assets/BossRoom/VFX/Materials/FX_M_Glow_14.mat
  Assets/BossRoom/VFX/Meshes/FX_Ms_Billboard.fbx
  Assets/BossRoom/VFX/Meshes/FX_Ms_SlahsShape.fbx
  Assets/BossRoom/VFX/Meshes/FX_Ms_SlashShape.fbx
  Assets/BossRoom/VFX/Meshes/FX_Ms_SlashShape.fbx.meta
  Assets/BossRoom/VFX/Meshes/FX_Slash.fbx
  Assets/BossRoom/VFX/Prefabs/Archer/FX_arrow.prefab
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ArrowGraphics.prefab
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow1Graphics.prefab
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow2Graphics.prefab
  Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow3Graphics.prefab
  Assets/BossRoom/VFX/Prefabs/Boss/FX_Boss_Charge_Motion_Hit.prefab
  Assets/BossRoom/VFX/Prefabs/Boss/FX_Boss_Leap_Weapon_Trail.prefab
  Assets/BossRoom/VFX/Prefabs/Imp/FX_IMP_attack_1_Slash.prefab
  Assets/BossRoom/VFX/Prefabs/Imp/FX_ImpDefeat.prefab
  Assets/BossRoom/VFX/Prefabs/Imp/Throw_bomb/FX_IMP_bomb_impact_big.prefab
  Assets/BossRoom/VFX/Prefabs/Shared Hero FX/FX_run_smoke.prefab
  Assets/BossRoom/VFX/Prefabs/Tank/fx_TankAttack1.prefab
Labels: 3-Good to Merge, type:feature

#468 fix: client writing to netvar error
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs
Labels: 2-Easy, 3-Good to Merge

#481 fix: connecting while starting game
  Assets/BossRoom/Scripts/Client/Game/State/ClientCharSelectState.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
Labels: 2-One More Review

#578 Fix/UI blocking pass
  Assets/BossRoom/Prefabs/UI/IPPopup.prefab
  Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
  Assets/BossRoom/Prefabs/UI/SettingsPanelCanvas.prefab
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
Labels: 2-Easy, 3-Good to Merge, priority:high, type:bug

#586 Fix: Character Shadow Simplification
  Assets/BossRoom/Prefabs/Shadow.prefab
Labels: 2-Easy, 3-Good to Merge

#482 feat: flag to prevent dev and release builds to connect
  Assets/BossRoom/Scripts/Client/UI/ConnectionStatusMessageUIManager.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs
Labels: 3-Good to Merge

#577 fix: Generate unique Profile ID on clone project
  Assets/BossRoom/Scripts/Shared/ProfileManager.cs
Labels: 2-Easy, 1-Needs Review

#576 feat: Environment layer pathing [MTT-2412], [MTT-2830], [MTT-1990]
  Assets/BossRoom/Prefabs/Dungeon/BossRoom.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/animated/env_door_boss_ani.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/animated/env_treasure_chest_ani.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_Door.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_barrier.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_pebbles.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_rock.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_spawn_door.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_torch.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_torch2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_corner_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_diagonal_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_diagonal_2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_diagonal_3.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_straight_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_straight_2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_straight_3.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_straight_cap_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_corner_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_diagonal_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_diagonal_2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_diagonal_3.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_straight_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_straight_2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_straight_3.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_wall1_top_straight_cap_1.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pots/env_pot_heavy.prefab
  Assets/BossRoom/Prefabs/Game/InteractiveBossDoor.prefab
  Assets/BossRoom/Prefabs/Game/StaticNetworkObjects/BossRoomStaticNetworkObjects.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scenes/BossRoom/NavMesh-DungeonNavMesh.asset
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerProjectileLogic.cs
  Assets/BossRoom/Scripts/Server/Navigation/DynamicNavPath.cs
  Assets/BossRoom/Scripts/Shared/Game/Action/ActionUtils.cs
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/TagManager.asset
Labels: 1-Needs Review
