Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2022-12, with the labels that each got.

#782 Boss Room v.2.0.3 and Utilities package 1.5.0 version bumps
  Assets/Readme.asset
  Assets/Scripts/UnityServices/Lobbies/LobbyAPIInterface.cs
  Assets/Scripts/UnityServices/Lobbies/LobbyServiceFacade.cs
  Assets/Scripts/VisualEffects/SpecialFXGraphic.cs
  Assets/VFX/Prefabs/Shared Hero FX/FX_Buff.prefab
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkAnimator.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkAnimator.cs.meta
  Packages/com.unity.multiplayer.samples.coop/package.json
  ProjectSettings/ProjectSettings.asset
  README.md
Labels: 2-Easy

#790 refactor: disconnect reason [MTT-2984] [MTT-5200]
  Assets/Scripts/ConnectionManagement/ConnectionManager.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectedState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientReconnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ConnectionState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/DisconnectingWithReasonState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/DisconnectingWithReasonState.cs.meta
  Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
  CHANGELOG.md
  Documentation/Images/BossRoomConnectionManager.png
  README.md
Labels: 2-Easy, 1-Needs Review

#791 chore: updating to ngo 1.2.0
  Assets/Scripts/ConnectionManagement/ConnectionManager.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectedState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientReconnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ConnectionState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/DisconnectingWithReasonState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/DisconnectingWithReasonState.cs.meta
  Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
  Assets/Tests/Runtime/ConnectionManagementTests.cs
  CHANGELOG.md
  Documentation/Images/BossRoomConnectionManager.png
  Packages/manifest.json
  Packages/packages-lock.json
  README.md
Labels: 2-Easy, 1-Needs Review

#769 Adding new entries to the index
  README.md
Labels: 2-Easy, 3-Good to Merge

#792 Adding profile manager reference to index
  README.md
Labels: 2-Easy, 1-Needs Review

#795 chore: updating to 2021.3.15f1
  CHANGELOG.md
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/ProjectVersion.txt
Labels: 0-URGENT, 2-Easy, 1-Needs Review

#796 chore: version bump
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/package.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#784 fix: EnemyPortals' VFX get disabled/enabled when crystals are broken [MTT-4893]
  Assets/Prefabs/Game/EnemySpawner.prefab
  Assets/Scripts/Gameplay/GameplayObjects/Breakable.cs
  Assets/Scripts/Gameplay/GameplayObjects/EnemyPortal.cs
  CHANGELOG.md
Labels: 2-Easy, 1-Needs Review

#785 fix: multiple warnings on insufficient AudioSources available [MTT-2834]
  Assets/Prefabs/CharGFX/PlayerGraphics_Rogue.prefab
  Assets/Prefabs/CharGFX/PlayerGraphics_Tank.prefab
  CHANGELOG.md
Labels: 2-Easy, 1-Needs Review

#786 chore: ClientCharacter TODO cleanup on anticipation [MTT-1744]
  Assets/Scripts/Gameplay/GameplayObjects/Character/ClientCharacter.cs
  CHANGELOG.md
Labels: 2-Easy, 1-Needs Review

#799 chore: Removing (now) redundant cached NetworkBehaviour status
  Assets/Scripts/Gameplay/GameplayObjects/Character/ClientCharacter.cs
  Assets/Scripts/Utils/NetworkOverlay/NetworkStats.cs
  CHANGELOG.md
Labels: 2-Easy, 3-Good to Merge

#798 feat: Adding build menus to automatically build all platforms for our platests
  Assets/Scripts/Editor/BuildHelpers.cs
  Assets/Scripts/Editor/BuildHelpers.cs.meta
Labels: 1-Needs Review
