Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2022-11, with the labels that each got.

#779 fix: hotfix: version bump to fix android build error
  CHANGELOG.md
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
Labels: 2-Easy, 1-Needs Review

#772 feat: host delete lobby when shutdown [MTT-4798] [MTT-4576]
  Assets/Scripts/UnityServices/Lobbies/LobbyAPIInterface.cs
  Assets/Scripts/UnityServices/Lobbies/LobbyServiceFacade.cs
  CHANGELOG.md
Labels: 3-Good to Merge, 2-hard

#780 feat: Adding ClientNetworkAnimator to samples utilities package [MTT-5025]
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkAnimator.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkAnimator.cs.meta
  README.md
Labels: 2-Easy, 3-Good to Merge
