Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2022-05, with the labels that each got.

#613 feat: connection feedback + IP connection window [MTT-2315] [MTT-3234]
  Assets/BossRoom/Prefabs/NetworkingManager.prefab
  Assets/BossRoom/Prefabs/UI/IPPopup.prefab
  Assets/BossRoom/Scripts/Client/UI/ConnectionStatusMessageUIManager.cs
  Assets/BossRoom/Scripts/Client/UI/IPConnectionWindow.cs
  Assets/BossRoom/Scripts/Client/UI/IPConnectionWindow.cs.meta
  Assets/BossRoom/Scripts/Client/UI/IPHostingUI.cs
  Assets/BossRoom/Scripts/Client/UI/IPJoiningUI.cs
  Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Labels: 1-Needs Review

#637 Feat: First Import of Vandal Imp Art[ [MTT-2732]
  Assets/BossRoom/GameData/Character/Imp/VandalImp.asset
  Assets/BossRoom/GameData/Character/Imp/VandalImp.asset.meta
  Assets/BossRoom/Material/Characters/Toon/Hair_Imp_Bomb.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Imp_Bomb.mat.meta
  Assets/BossRoom/Material/Characters/Toon/Head_Imp_Bomb.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Imp_Bomb.mat.meta
  Assets/BossRoom/Material/Characters/Toon/Helmet_Imp.mat
  Assets/BossRoom/Material/Characters/Toon/Helmet_Imp.mat.meta
  Assets/BossRoom/Material/Characters/Toon/Torso_Imp_Bomb.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Imp_Bomb.mat.meta
  Assets/BossRoom/Material/Characters/Toon/Weapons_VandalImp.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_VandalImp.mat.meta
  Assets/BossRoom/Models/Animation Controllers/CharacterSetController_VandalImp.overrideController
  Assets/BossRoom/Models/Animation Controllers/CharacterSetController_VandalImp.overrideController.meta
  Assets/BossRoom/Models/CharacterSet.fbx
  Assets/BossRoom/Prefabs/CharGFX/VandalImpGraphics.prefab
  Assets/BossRoom/Prefabs/CharGFX/VandalImpGraphics.prefab.meta
  Assets/BossRoom/Prefabs/Character/VandalImp.prefab
  Assets/BossRoom/Prefabs/Character/VandalImp.prefab.meta
  Assets/BossRoom/Prefabs/NetworkingManager.prefab
  Assets/BossRoom/Textures/Characters/Boss_Torso_CLR.tga
  Assets/BossRoom/Textures/Characters/Imp_Helmet_CLR.tga
  Assets/BossRoom/Textures/Characters/Imp_Helmet_CLR.tga.meta
  Assets/BossRoom/Textures/Characters/Imp_Weapons_CLR.tga
  Assets/BossRoom/Textures/Characters/VandalImp_Head_CLR.tga
  Assets/BossRoom/Textures/Characters/VandalImp_Head_CLR.tga.meta
  Assets/BossRoom/Textures/Characters/VandalImp_Torso_CLR.tga
  Assets/BossRoom/Textures/Characters/VandalImp_Torso_CLR.tga.meta
Labels: 2-Easy, 3-Good to Merge, type:feature

#639 fix: testing package constraint addition to unblock builds
  Packages/com.unity.multiplayer.samples.coop/Utilities/Testing/com.unity.multiplayer.samples.utilities.testing.asmdef
Labels: 0-URGENT, 1-Needs Review

#580 feat: other players loading progress in loading screen [MTT-2239]
  Assets/BossRoom/Prefabs/LoadingProgressTracker.prefab
  Assets/BossRoom/Prefabs/LoadingProgressTracker.prefab.meta
  Assets/BossRoom/Prefabs/NetworkingManager.prefab
  Assets/BossRoom/Prefabs/SceneLoader.prefab
  Assets/BossRoom/Prefabs/UI/LoadingScreen.prefab
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Client/UI/ClientBossRoomLoadingScreen.cs
  Assets/BossRoom/Scripts/Client/UI/ClientBossRoomLoadingScreen.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ClientLoadingScreen.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/LoadingProgressManager.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/LoadingProgressManager.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/NetworkedLoadingProgressTracker.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/NetworkedLoadingProgressTracker.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
Labels: 1-Needs Review

#611 feat: auto reconnect [MTT-2617]
  Assets/BossRoom/Prefabs/NetworkingManager.prefab
  Assets/BossRoom/Prefabs/UI/IPPopup.prefab
  Assets/BossRoom/Prefabs/UI/LoadingSpinner.prefab
  Assets/BossRoom/Prefabs/UI/LoadingSpinner.prefab.meta
  Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
  Assets/BossRoom/Prefabs/UI/PopupPanel.prefab
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientCharSelectState.cs
  Assets/BossRoom/Scripts/Client/UI/ConnectionStatusMessageUIManager.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/PopupManager.cs
  Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ServerAdditiveSceneLoader.cs
Labels: 1-Needs Review

#641 hotfix: moving scenebootstrapper to re-enable builds
  Assets/BossRoom/Scripts/Editor/SceneBootstrapper.cs
  Assets/BossRoom/Scripts/Editor/SceneBootstrapper.cs.meta
Labels: 2-Easy, 3-Good to Merge

#621 feat: adding RNSM to boss room [MTT-3267]
  Assets/BossRoom/Scenes/Startup.unity
  Packages/com.unity.multiplayer.samples.coop/Utilities/DontDestroyOnLoad.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/DontDestroyOnLoad.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/AutoHide.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/AutoHide.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/NetStatsMonitorCustomization.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/NetStatsMonitorCustomization.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/NetStatsMonitorPrefab.prefab
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/NetStatsMonitorPrefab.prefab.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/com.unity.multiplayer.samples.utilities.asmdef
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 0-URGENT, 2-One More Review

#640 chore: formatting pass
  .editorconfig
  Assets/BossRoom/Scripts/Game/Client/Character/ClientCharacterVisualization.cs
  Assets/BossRoom/Scripts/Game/Client/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Game/Client/ClientClickFeedback.cs
  Assets/BossRoom/Scripts/Game/Client/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Game/Client/UI/ConnectionStatusMessageUIManager.cs
  Assets/BossRoom/Scripts/Game/Client/UI/IPConnectionWindow.cs
  Assets/BossRoom/Scripts/Game/Client/UI/Lobby/LobbyJoiningUI.cs
  Assets/BossRoom/Scripts/Game/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Game/ConnectionManagement/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Game/Server/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Game/Server/Entity/PublishMessageOnLifeChange.cs
  Assets/BossRoom/Scripts/Infrastructure/DIScope.cs
  Assets/BossRoom/Scripts/Infrastructure/PubSub/MessageChannel.cs
  Assets/BossRoom/Scripts/Infrastructure/UpdateRunner.cs
  Assets/BossRoom/Scripts/UnityServices/Lobbies/JoinedLobbyContentHeartbeat.cs
  Assets/BossRoom/Scripts/UnityServices/Lobbies/LobbyAPIInterface.cs
  Assets/BossRoom/Scripts/UnityServices/Lobbies/LobbyServiceFacade.cs
  Assets/BossRoom/Scripts/UnityServices/Lobbies/LocalLobbyUser.cs
  Assets/BossRoom/Scripts/UnityServices/Lobbies/Messages/LobbyListFetchedMessage.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ClientLoadingScreen.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/NetworkedLoadingProgressTracker.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
Labels: 2-Easy, 3-Good to Merge

#643 chore: bump NGO to pre.9
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 2-Easy, 3-Good to Merge

#642 Fixing 2021 new serialization and adding default namespace to editor settings
  Assets/BossRoom/Material/Characters/Toon/Hair_Rogue_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Hair_Rogue_Girl.mat
  Assets/BossRoom/Material/Characters/Toon/Head_Rogue_Boy.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Imp.mat
  Assets/BossRoom/Material/Characters/Toon/Torso_Rogue.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Imp.mat
  Assets/BossRoom/Material/Characters/Toon/Weapons_Rogue.mat
  Assets/BossRoom/VFX/Materials/FX_M_StylizeSmoke.mat
  ProjectSettings/EditorSettings.asset
Labels: 2-Easy, 3-Good to Merge

#649 chore: adding template instructions and updating how we update our changelogs
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
Labels: 2-Easy, 1-Needs Review

#636 feat: change profile in-game [MTT-2809]
  Assets/BossRoom/Prefabs/UI/ProfilePopup.prefab
  Assets/BossRoom/Prefabs/UI/ProfilePopup.prefab.meta
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scripts/Game/ApplicationController.cs
  Assets/BossRoom/Scripts/Game/Client/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Game/Client/UI/ProfileListItemUI.cs
  Assets/BossRoom/Scripts/Game/Client/UI/ProfileListItemUI.cs.meta
  Assets/BossRoom/Scripts/Game/Client/UI/UIProfileSelector.cs
  Assets/BossRoom/Scripts/Game/Client/UI/UIProfileSelector.cs.meta
  Assets/BossRoom/Scripts/Game/Client/UI/UnityServicesUIHandler.cs
  Assets/BossRoom/Scripts/Game/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Infrastructure/ClientPrefs.cs
  Assets/BossRoom/Scripts/Infrastructure/ProfileManager.cs
  Assets/BossRoom/Scripts/UnityServices/Auth/AuthenticationServiceFacade.cs
Labels: 3-Good to Merge

#638 chore: remove UNET [MTT-3435]
  ARCHITECTURE.md
  Assets/BossRoom/Prefabs/NetworkingManager.prefab
  Assets/BossRoom/Scripts/Game/Client/UI/IPConnectionWindow.cs
  Assets/BossRoom/Scripts/Game/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Game/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Game/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Game/Shared/TransportPicker.cs
  Assets/BossRoom/Scripts/Game/Shared/TransportPicker.cs.meta
  Assets/BossRoom/Scripts/Infrastructure/Editor/NetworkLatencyWarning.cs
Labels: 2-Easy, 2-One More Review

#644 fix: not enough progress bars exception [MTT-3499]
  Assets/BossRoom/Prefabs/UI/LoadingScreen.prefab
  Assets/BossRoom/Scripts/Game/Client/UI/ClientBossRoomLoadingScreen.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ClientLoadingScreen.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/LoadingProgressManager.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
Labels: 2-One More Review

#650 fix: remove initial ugs popup [MTT-3563]
  Assets/BossRoom/Prefabs/UI/MainMenu UI Canvas.prefab
  Assets/BossRoom/Prefabs/UI/MainMenu UI Canvas.prefab.meta
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scripts/Game/Client/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Game/Client/UI/UITooltipDetector.cs
  CHANGELOG.md
Labels: 3-Good to Merge

#652 docs: update readmes for new flow [MTT-3573]
  Assets/Readme.asset
  README.md
Labels: 2-Easy, 2-One More Review

#655 fix: unregister profile manager callback [MTT-3585]
  Assets/BossRoom/Scripts/Game/Client/State/ClientMainMenuState.cs
Labels: 2-Easy, 3-Good to Merge

#654 fix: loading progress bars mismatch [MTT-3616]
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ClientLoadingScreen.cs
Labels: 3-Good to Merge

#653 feat: editor child scene loader for composed scenes
  Assets/BossRoom/Scenes/BossRoom.unity
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/EditorChildSceneLoader.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/EditorChildSceneLoader.cs.meta
Labels: 1-Needs Review

#657 feat: Bumping relay version with qos
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/UnityRelayUtilities.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
Labels: 2-Easy, 2-One More Review

#658 fix: auth signin error on startup [MTT-3581]
  Assets/BossRoom/Scripts/Game/Client/UI/Lobby/LobbyJoiningUI.cs
Labels: 2-Easy, 3-Good to Merge

#632 feat: bad network conditions warning [MTT-3242]
  Assets/BossRoom/Prefabs/Debug Overlay Canvas.prefab
  Assets/BossRoom/Scripts/Infrastructure/Editor/NetworkLatencyWarning.cs
  Assets/BossRoom/Scripts/Infrastructure/Editor/NetworkOverlay.cs
  Assets/BossRoom/Scripts/Infrastructure/NetworkStats.cs
  CHANGELOG.md
Labels: 2-Easy, 2-One More Review

#635 fix: reduced scene load timeout
  Assets/BossRoom/Prefabs/NetworkingManager.prefab
Labels: 2-Easy, 3-Good to Merge

#662 Fix: Char Select UI Collision [MTT-3680]
  Assets/BossRoom/Prefabs/UI/CharacterSelectCanvas.prefab
Labels: 2-Easy, 3-Good to Merge, type:bug

#663 Fix: Broken Shader References [MTT-3681]
  Assets/BossRoom/VFX/Materials/FX_M_GroundCrack_01.mat
  Assets/BossRoom/VFX/Materials/FX_M_GroundCrack_02.mat
  Assets/BossRoom/VFX/Materials/FX_M_ImpExplosionFire.mat
  Assets/BossRoom/VFX/Materials/FX_M_Shockwave.mat
  Assets/BossRoom/VFX/Materials/FX_M_SmokeDissolveMultip.mat
  Assets/BossRoom/VFX/Materials/FX_M_Snowflake_Additive.mat
  Assets/BossRoom/VFX/Materials/FX_M_Sparks.mat
  Assets/BossRoom/VFX/Materials/FX_M_StylizeSmoke_02.mat
  Assets/BossRoom/VFX/Materials/FX_M_StylizeSmoke_Falldown.mat
  Assets/BossRoom/VFX/Materials/FX_M_Trail_01.mat
  Assets/BossRoom/VFX/Materials/FX_M_Trail_02.mat
  Assets/BossRoom/VFX/Materials/FX_M_Wave_01.mat
Labels: 2-Easy, 3-Good to Merge

#665 Fix: Glowing Eyes on Low Quality Setting on Android [MTT-3688]
  Assets/BossRoom/Material/Characters/Enemy_Eyes_sheet.mat
  Assets/BossRoom/Material/Characters/Enemy_Mouth_sheet.mat
  Assets/BossRoom/Material/Characters/Hero_Eyes_sheet.mat
  Assets/BossRoom/Material/Characters/Hero_Mouth_sheet.mat
Labels: 2-Easy, 3-Good to Merge

#664 Fix: Flickering Artifacts on Boss Room Title in Post Game Scene [MTT-3687]
  Assets/BossRoom/Scenes/PostGame.unity
Labels: 2-Easy, 3-Good to Merge

#667 fix: no popup when incompatible build types [MTT-3689]
  Assets/BossRoom/Scripts/Game/ConnectionManagement/ClientGameNetPortal.cs
Labels: 0-URGENT, 2-Easy, 3-Good to Merge
