Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2022-10, with the labels that each got.

#755 Updating readme with Typeform for feedback
  Assets/Readme.asset
  README.md
Labels: 0-URGENT, 2-Easy, 2-One More Review

#746 chore: adding details to changelog
  CHANGELOG.md
Labels: 0-URGENT, 2-One More Review

#756 Adding link to feedback form at the top
  README.md
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#757 adding components refs to index
  README.md
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#758 Updating broken PR links (shouldn't be linked to jira)
  CHANGELOG.md
Labels: 0-URGENT, 2-Easy, 1-Needs Review

#761 Version bumps
  CHANGELOG.md
  ProjectSettings/ProjectSettings.asset
Labels: 0-URGENT, 2-Easy, 2-One More Review

#764 Updating utilities package for release
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/QAReport.md
  Packages/com.unity.multiplayer.samples.coop/QAReport.md.meta
  Packages/com.unity.multiplayer.samples.coop/README.md
  Packages/com.unity.multiplayer.samples.coop/package.json
Labels: 0-URGENT, 2-Easy, 2-One More Review

#759 Update README.md
  README.md
Labels: 0-URGENT, 2-Easy, 1-Needs Review

#754 fix: removing FindObjectOfType for a serialized reference
  Assets/Prefabs/State/CharSelectState.prefab
  Assets/Scripts/Gameplay/GameState/ClientCharSelectState.cs
  CHANGELOG.md
Labels: 2-Easy, 2-One More Review

#762 Fix: Enabled Depth Buffer in URP Settings
  Assets/URP/Mobile/0_UniversalRenderPipelineAsset_Mobile_Low.asset
  Assets/URP/Mobile/1_UniversalRenderPipelineAsset_Mobile_Medium.asset
  Assets/URP/Mobile/2_UniversalRenderPipelineAsset_Mobile_High.asset
  Assets/URP/Mobile/2_UniversalRenderPipelineAsset_Renderer_Mobile_High.asset
  Assets/URP/UniversalRenderPipelineAsset.asset
  Assets/URP/UniversalRenderPipelineAsset.asset.meta
  Assets/URP/UniversalRenderPipelineAsset_Renderer.asset
  Assets/URP/UniversalRenderPipelineAsset_Renderer.asset.meta
  Assets/URP/Windows/0_UniversalRenderPipelineAsset_Windows_Low.asset
  Assets/URP/Windows/1_UniversalRenderPipelineAsset_Windows_Medium.asset
  Assets/URP/Windows/2_UniversalRenderPipelineAsset_Windows_High.asset
  Assets/URP/Windows/3_UniversalRenderPipelineAsset_Windows_Ultra.asset
  CHANGELOG.md
Labels: 2-Easy, 3-Good to Merge

#768 Fix: Moved Clipping Torch
  Assets/Scenes/BossRoom/DungeonEntrance.unity
  CHANGELOG.md
Labels: 2-Easy, 2-One More Review

#770 fix: making key press 1 revive and pickup/drop pots [MTT-4802]
  Assets/Prefabs/Character/PlayerAvatar.prefab
  Assets/Scripts/Gameplay/GameplayObjects/RuntimeDataContainers/GameDataSource.cs
  Assets/Scripts/Gameplay/UI/HeroActionBar.cs
  Assets/Scripts/Gameplay/UI/HeroEmoteBar.cs
  Assets/Scripts/Gameplay/UI/PartyHUD.cs
  Assets/Scripts/Gameplay/UserInput/ClientInputSender.cs
  CHANGELOG.md
Labels: 2-One More Review

#708 feat: bumping boss room to 1.1
  Assets/Prefabs/NetworkingManager.prefab
  Assets/Scripts/ConnectionManagement/ConnectionMethod.cs
  Assets/Scripts/ConnectionManagement/ConnectionMethod.cs.meta
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientReconnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/OfflineState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/OnlineState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/StartingHostState.cs
  Assets/Scripts/ConnectionManagement/Unity.BossRoom.ConnectionManagement.asmdef
  Assets/Scripts/Gameplay/GameplayObjects/Breakable.cs
  Assets/Scripts/Infrastructure/NetworkGuid.cs
  Assets/Tests/Runtime/NetworkedMessageChannelTests.cs
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/UnityRelayUtilities.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/LoadingProgressManager.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
  Packages/com.unity.multiplayer.samples.coop/package.json
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 2-One More Review

#774 chore: update version numbers
  Packages/com.unity.multiplayer.samples.coop/package.json
  ProjectSettings/ProjectSettings.asset
Labels: 0-URGENT, 2-Easy, 1-Needs Review

#771 fix: mage heal fx plays out for whole duration & stays at spawn rotation [MTT-4476]
  Assets/Scripts/VisualEffects/SpecialFXGraphic.cs
  Assets/VFX/Prefabs/Shared Hero FX/FX_Buff.prefab
  CHANGELOG.md
Labels: 2-Easy, 2-One More Review

#777 chore: replacing "template" for "sample" [MTT-5003]
  Assets/Readme.asset
Labels: 2-Easy, 3-Good to Merge
