Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2022-02, with the labels that each got.

#456 feat: update to ngo 1.0.0-pre.5
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
  ProjectSettings/CommonBurstAotSettings.json
Labels: URGENT, One More Review

#435 fix: client not properly disconnecting when host disconnects, quits or crashes
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
Labels: URGENT, Good to Merge

#432 feat: disconnect/quit button
  Assets/BossRoom/Prefabs/UI/CharacterSelectCanvas.prefab
  Assets/BossRoom/Prefabs/UI/SettingsPanelCanvas.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientCharSelectState.cs
  Assets/BossRoom/Scripts/Client/UI/UIQuitPanel.cs
  Assets/BossRoom/Scripts/Client/UI/UIQuitPanel.cs.meta
  Assets/BossRoom/Scripts/Client/UI/UISettingsCanvas.cs
  Assets/BossRoom/Scripts/Shared/Game/Action/ActionUtils.cs
Labels: URGENT, One More Review

#455 fix: cheat window toggling on mobile
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
Labels: URGENT, Good to Merge

#457 fix: cannot host a game after having previously played as a client
  Assets/BossRoom/Scripts/Server/Game/Character/PlayerServerCharacter.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Labels: URGENT, Easy, Good to Merge

#436 fix: more responsive actions
  Assets/BossRoom/GameData/Action/Archer/ArcherBaseAttack.asset
  Assets/BossRoom/GameData/Action/Boss/BossImpBaseAttack.asset
  Assets/BossRoom/GameData/Action/Boss/BossImpTrampleAttack.asset
  Assets/BossRoom/GameData/Action/Imp/ImpBaseAttack.asset
  Assets/BossRoom/GameData/Action/Mage/MageBaseAttack.asset
  Assets/BossRoom/GameData/Action/Mage/MageHeal.asset
  Assets/BossRoom/GameData/Action/Rogue/RogueBaseAttack.asset
  Assets/BossRoom/GameData/Action/Rogue/RogueDashAttack.asset
  Assets/BossRoom/GameData/Action/Tank/TankBaseAttack.asset
  Assets/BossRoom/GameData/Action/Tank/TankShieldBuff.asset
  Assets/BossRoom/GameData/Character/Archer/Archer.asset
  Assets/BossRoom/GameData/Character/Imp/Imp.asset
  Assets/BossRoom/GameData/Character/ImpBoss/ImpBoss.asset
  Assets/BossRoom/GameData/Character/Mage/Mage.asset
  Assets/BossRoom/GameData/Character/Rogue/Rogue.asset
  Assets/BossRoom/GameData/Character/Tank/Tank.asset
  Assets/BossRoom/Models/Animation Controllers/CharacterSetController.controller
  Assets/BossRoom/Models/Animation Controllers/DoorController.controller
  Assets/BossRoom/Prefabs/CharGFX/PlayerGraphics_Rogue.prefab
  Assets/BossRoom/VFX/Materials/FX_Slash_01.mat
  Assets/BossRoom/VFX/Prefabs/Rogue/FX_Rogue_attack_1_Slash.prefab
  Assets/BossRoom/VFX/Prefabs/Tank/fx_TankAttack1.prefab
Labels: URGENT, Good to Merge

#465 fix: dotnet format over solution based on project's .editorconfig file
  Assets/BossRoom/Scripts/Client/AnimationCallbacks/AnimatorTriggeredSpecialFX.cs
  Assets/BossRoom/Scripts/Client/Audio/BossMusicStarter.cs
  Assets/BossRoom/Scripts/Client/Audio/ClientMusicPlayer.cs
  Assets/BossRoom/Scripts/Client/Game/Action/ActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/ActionVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/MeleeActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/TargetActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientPlayerAvatar.cs
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientAvatarGuidHandler.cs
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientBreakableVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientProjectileVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/State/ClientBossRoomState.cs
  Assets/BossRoom/Scripts/Client/Game/State/ClientCharSelectState.cs
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/HeroEmoteBar.cs
  Assets/BossRoom/Scripts/Client/UI/MainMenuUI.cs
  Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs
  Assets/BossRoom/Scripts/Client/UI/QualityButton.cs
  Assets/BossRoom/Scripts/Editor/BakingMenu.cs
  Assets/BossRoom/Scripts/Editor/Readme/Readme.cs
  Assets/BossRoom/Scripts/Editor/Readme/ReadmeEditor.cs
  Assets/BossRoom/Scripts/Server/Game/Action/Action.cs
  Assets/BossRoom/Scripts/Server/Game/Action/ActionPlayer.cs
  Assets/BossRoom/Scripts/Server/Game/Action/ChaseAction.cs
  Assets/BossRoom/Scripts/Server/Game/Action/FXProjectileTargetedAction.cs
  Assets/BossRoom/Scripts/Server/Game/Action/MeleeAction.cs
  Assets/BossRoom/Scripts/Server/Game/Action/TrampleAction.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/IDamageable.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
  Assets/BossRoom/Scripts/Server/Navigation/DynamicNavPath.cs
  Assets/BossRoom/Scripts/Server/Navigation/NavigationSystem.cs
  Assets/BossRoom/Scripts/Shared/Data/ActionDescription.cs
  Assets/BossRoom/Scripts/Shared/Data/GameDataSource.cs
  Assets/BossRoom/Scripts/Shared/Game/Action/BaseActionInput.cs
  Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkBreakableState.cs
  Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs
  Assets/BossRoom/Scripts/Shared/Game/State/CharSelectData.cs
  Assets/BossRoom/Scripts/Shared/Game/UI/Editor/NetworkLatencyWarning.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/DisconnectReason.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/NetworkStats.cs
  Assets/BossRoom/Scripts/Shared/NetworkNameState.cs
  Packages/com.unity.multiplayer.samples.coop/Tests/Editor/EditorExampleTest.cs
  Packages/com.unity.multiplayer.samples.coop/Tests/Runtime/RuntimeExampleTest.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/UnityRelayUtilities.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Test.cs
Labels: Easy, One More Review

#469 Fixed a broken material ref on boss pillars
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar2.prefab
  Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar2_break_parent.prefab
Labels: 0-URGENT, Easy, One More Review

#459 Fix/bossroom anim edits
  Assets/BossRoom/Models/CharacterSet.fbx
  Assets/BossRoom/Models/CharacterSet.fbx.meta
Labels: One More Review

#467 feat: upgrade editor LTS version to 2020.3.27
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
Labels: 0-URGENT, Easy, Needs Review

#470 Fix: Background missing in Post Game scene
  Assets/BossRoom/Scenes/PostGame.unity
Labels: Easy, One More Review

#472 Fix/randomly rotate breakable pots
  Assets/BossRoom/Prefabs/Game/StaticNetworkObjects/BossRoomStaticNetworkObjects.prefab
  Assets/BossRoom/Prefabs/Game/StaticNetworkObjects/EntranceStaticNetworkObjects.prefab
  Assets/BossRoom/Prefabs/Game/StaticNetworkObjects/TransitionAreaStaticNetworkObjects.prefab
Labels: Easy, Needs Review

#471 Deleted an overlapping object
  Assets/BossRoom/Prefabs/Dungeon/TransitionArea.prefab
Labels: Easy, One More Review

#474 version bump
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 0-URGENT, 2-Easy, 2-One More Review

#464 feat: code formatting Yamato job and dotnet format project
  .yamato/project-standards.yml
  .yamato/project.metafile
  .yamato/upm-ci.yml
  dotnet-tools/.gitignore
  dotnet-tools/README.md
  dotnet-tools/netcode.standards/Program.cs
  dotnet-tools/netcode.standards/netcode.standards.csproj
Labels: 3-Good to Merge

#478 fix: react anim on trample attack while fainted
  Assets/BossRoom/Scripts/Server/Game/Action/TrampleAction.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/DamageReceiver.cs
Labels: 2-Easy, 2-One More Review

#446 feat: add buttons to cheat window
  Assets/BossRoom/Prefabs/UI/BossRoomHudCanvas.prefab
  Assets/BossRoom/Prefabs/UI/CheatButton.prefab
  Assets/BossRoom/Prefabs/UI/CheatButton.prefab.meta
  Assets/BossRoom/Prefabs/UI/CheatsPopupPanel.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
  Assets/BossRoom/Scripts/Server/Game/Character/PlayerServerCharacter.cs
Labels: 2-Easy, 2-One More Review
