Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2022-08, with the labels that each got.

#670 feat: allowing users to subscribe to a networked message channel while offline [MTT-3684] [MTT-3690]
  Assets/Scripts/ApplicationLifecycle/ApplicationController.cs
  Assets/Scripts/Infrastructure/PubSub/NetworkedMessageChannel.cs
  Assets/Scripts/Infrastructure/Unity.BossRoom.Infrastructure.asmdef
  Assets/Tests/Runtime/NetworkedMessageChannelTests.cs
  Assets/Tests/Runtime/NetworkedMessageChannelTests.cs.meta
  Assets/Tests/Runtime/Unity.BossRoom.Tests.Runtime.asmdef
  CHANGELOG.md
  Packages/manifest.json
Labels: 3-Good to Merge

#699 fix: removing redundant lobby refresh and unsubscribing from lobby queries [MTT-4018]
  Assets/Scripts/Gameplay/UI/Lobby/LobbyJoiningUI.cs
  Assets/Scripts/Gameplay/UI/Lobby/LobbyUIMediator.cs
Labels: 2-Easy, 3-Good to Merge

#703 fix: restoring lobby heartbeat [MTT-4210]
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectedState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
Labels: 2-Easy, 3-Good to Merge

#697 feat: removing bridge classes for game states MTT-4204
  Assets/GameData/Transforms.meta
  Assets/GameData/Transforms/NetworkGameState.asset
  Assets/GameData/Transforms/NetworkGameState.asset.meta
  Assets/Prefabs/Game/NetworkGameState.prefab
  Assets/Prefabs/Game/NetworkGameState.prefab.meta
  Assets/Prefabs/State/BossRoomState.prefab
  Assets/Prefabs/State/PostGameState.prefab
  Assets/Scenes/BossRoom.unity
  Assets/Scenes/BossRoom/DungeonBossRoom.unity
  Assets/Scenes/BossRoom/DungeonEntrance.unity
  Assets/Scenes/BossRoom/DungeonTransition.unity
  Assets/Scenes/PostGame.unity
  Assets/Scripts/ConnectionManagement/ConnectionManager.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
  Assets/Scripts/Gameplay/GameState/ClientBossRoomState.cs
  Assets/Scripts/Gameplay/GameState/ClientBossRoomState.cs.meta
  Assets/Scripts/Gameplay/GameState/ClientPostGameState.cs
  Assets/Scripts/Gameplay/GameState/ClientPostGameState.cs.meta
  Assets/Scripts/Gameplay/GameState/GameStateBehaviour.cs
  Assets/Scripts/Gameplay/GameState/NetworkGameState.cs
  Assets/Scripts/Gameplay/GameState/NetworkWinState.cs.meta
  Assets/Scripts/Gameplay/GameState/PersistentGameState.cs
  Assets/Scripts/Gameplay/GameState/PersistentGameState.cs.meta
  Assets/Scripts/Gameplay/GameState/ServerBossRoomState.cs
  Assets/Scripts/Gameplay/GameState/ServerPostGameState.cs
  Assets/Scripts/Gameplay/GameplayObjects/ClientDoorVisualization.cs
  Assets/Scripts/Gameplay/UI/PostGameUI.cs
  CHANGELOG.md
Labels: 2-Easy, 3-Good to Merge

#711 Feat: Profile Analyzer Package [Skip CI]
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 2-Easy, 3-Good to Merge

#702 fix: using Visible instead of enabled to make sure RNSM continues updating when off
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/NetStatsMonitorCustomization.cs
Labels: 2-Easy, 3-Good to Merge

#372 feat: NetworkObject parenting, PickUp Action [MTT-992]
  Assets/GameData/Action/General/Drop.asset
  Assets/GameData/Action/General/Drop.asset.meta
  Assets/GameData/Action/General/PickUp.asset
  Assets/GameData/Action/General/PickUp.asset.meta
  Assets/Models/Animation Controllers/CharacterSetController.controller
  Assets/Prefabs/CharGFX/CharacterGraphics/PlayerGraphics_Archer_Boy.prefab
  Assets/Prefabs/CharGFX/CharacterGraphics/PlayerGraphics_Archer_Girl.prefab
  Assets/Prefabs/CharGFX/CharacterGraphics/PlayerGraphics_Mage_Boy.prefab
  Assets/Prefabs/CharGFX/CharacterGraphics/PlayerGraphics_Mage_Girl.prefab
  Assets/Prefabs/CharGFX/CharacterGraphics/PlayerGraphics_Rogue_Boy.prefab
  Assets/Prefabs/CharGFX/CharacterGraphics/PlayerGraphics_Rogue_Girl.prefab
  Assets/Prefabs/CharGFX/CharacterGraphics/PlayerGraphics_Tank_Boy.prefab
  Assets/Prefabs/CharGFX/CharacterGraphics/PlayerGraphics_Tank_Girl.prefab
  Assets/Prefabs/Character/PlayerAvatar.prefab
  Assets/Prefabs/Game/PickUpPot.prefab
  Assets/Prefabs/Game/PickUpPot.prefab.meta
  Assets/Prefabs/Game/StaticNetworkObjects/EntranceStaticNetworkObjects.prefab
  Assets/Prefabs/GameDataSource.prefab
  Assets/Prefabs/NetworkingManager.prefab
  Assets/Scenes/BossRoom/DungeonEntrance.unity
  Assets/Scripts/Gameplay/Action/Action.cs
  Assets/Scripts/Gameplay/Action/ActionFX.cs
  Assets/Scripts/Gameplay/Action/ActionPlayer.cs
  Assets/Scripts/Gameplay/Action/ActionRequestData.cs
  Assets/Scripts/Gameplay/Action/DropAction.cs
  Assets/Scripts/Gameplay/Action/DropAction.cs.meta
  Assets/Scripts/Gameplay/Action/PickUpAction.cs
  Assets/Scripts/Gameplay/Action/PickUpAction.cs.meta
  Assets/Scripts/Gameplay/Configuration/ActionDescription.cs
  Assets/Scripts/Gameplay/GameplayObjects/Character/CharacterSwap.cs
  Assets/Scripts/Gameplay/GameplayObjects/Character/ClientCharacterVisualization.cs
  Assets/Scripts/Gameplay/GameplayObjects/Character/ServerCharacter.cs
  Assets/Scripts/Gameplay/GameplayObjects/NetworkCharacterState.cs
  Assets/Scripts/Gameplay/GameplayObjects/PickUpState.cs
  Assets/Scripts/Gameplay/GameplayObjects/PickUpState.cs.meta
  Assets/Scripts/Gameplay/GameplayObjects/ServerDisplacerOnParentChange.cs
  Assets/Scripts/Gameplay/GameplayObjects/ServerDisplacerOnParentChange.cs.meta
  Assets/Scripts/Gameplay/GameplayObjects/ServerProjectileLogic.cs
  Assets/Scripts/Gameplay/Input/ClientInputSender.cs
  Assets/Scripts/Gameplay/UI/HeroActionBar.cs
  CHANGELOG.md
Labels: 3-Good to Merge, type:feature

#714 fix: VContainer injection issue
  Assets/Scenes/BossRoom/DungeonBossRoom.unity
  Assets/Scenes/BossRoom/DungeonEntrance.unity
  Assets/Scenes/BossRoom/DungeonTransition.unity
Labels: 1-Needs Review

#707 feat: returning to offline state on transport failure [MTT-4302]
  Assets/Scripts/ConnectionManagement/ConnectionManager.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientReconnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ConnectionState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/DisconnectingWithReasonState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/OnlineState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/OnlineState.cs.meta
  Assets/Scripts/ConnectionManagement/ConnectionState/StartingHostState.cs
  CHANGELOG.md
Labels: 2-Easy, 3-Good to Merge

#718 fix: disabling NetworkBehaviours instead of destroying them [MTT-4481]
  Assets/Scripts/Gameplay/Input/ClientClickFeedback.cs
  Assets/Scripts/Utils/NetworkOverlay/NetworkStats.cs
  CHANGELOG.md
Labels: 2-Easy, 2-One More Review

#719 fix: game frozen when client leaves in postgame [MTT-4342]
  Assets/Scripts/Gameplay/GameState/ServerBossRoomState.cs
Labels: 2-Easy, 3-Good to Merge

#717 feat: NetworkObjectSpawner for dynamically spawning in-scene placed NetworkObjects [MTT-1558]
  Assets/Prefabs/CharGFX/VandalImpGraphics.prefab
  Assets/Prefabs/Game/NetworkObjectSpawner.prefab
  Assets/Prefabs/Game/NetworkObjectSpawner.prefab.meta
  Assets/Prefabs/Game/StaticNetworkObjects/BossRoomStaticNetworkObjects.prefab
  Assets/Prefabs/Game/StaticNetworkObjects/EntranceStaticNetworkObjects.prefab
  Assets/Prefabs/Game/StaticNetworkObjects/TransitionAreaStaticNetworkObjects.prefab
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/NetworkObjectSpawner.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/NetworkObjectSpawner.cs.meta
Labels: 2-One More Review

#720 ngo 1.0.1 bump
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/package.json
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
Labels: 2-Easy, 3-Good to Merge

#722 fix: NetworkTransform reference on PickupPot re-hooked up
  Assets/Prefabs/Game/PickUpPot.prefab
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#712 Feature: LODs Setup on Dense Meshes [MTT-4451]
  Assets/Models/DungeonPieces.FBX
  Assets/Models/DungeonPieces.FBX.meta
  Assets/Prefabs/Dungeon/BossRoom.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_Door.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_banner.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_barrier.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_door_crystral_base.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_floor6.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_floor_barrier_1.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_pebbles.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_roots.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_spawn_door.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_torch2.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar2.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/pots/env_pot.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/pots/env_pot_heavy.prefab
  Assets/Prefabs/Dungeon/Entrance.prefab
  Assets/Prefabs/Game/BreakableCrystal.prefab
  Assets/Prefabs/Game/EnemySpawner.prefab
  Assets/Scenes/BossRoom/DungeonBossRoom.unity
  Assets/Scenes/BossRoom/LightingData.asset
  Assets/Scenes/BossRoom/Lightmap-0_comp_light.exr
  Assets/Scenes/BossRoom/Lightmap-0_comp_light.exr.meta
  Assets/Scenes/BossRoom/Lightmap-1_comp_light.exr
  Assets/Scenes/BossRoom/Lightmap-1_comp_light.exr.meta
  Assets/Scenes/BossRoom/Lightmap-2_comp_light.exr
  Assets/Scenes/BossRoom/Lightmap-2_comp_light.exr.meta
  Assets/Scenes/BossRoom/Lightmap-3_comp_light.exr
  Assets/Scenes/BossRoom/Lightmap-3_comp_light.exr.meta
  Assets/Scenes/BossRoom/Lightmap-4_comp_light.exr
  Assets/Scenes/BossRoom/Lightmap-4_comp_light.exr.meta
  Assets/Scenes/BossRoom/Lightmap-5_comp_light.exr
  Assets/Scenes/BossRoom/Lightmap-5_comp_light.exr.meta
  Assets/Scenes/BossRoom/ReflectionProbe-0.png
  Assets/Scenes/BossRoom/ReflectionProbe-0.png.meta
  Assets/Scenes/BossRoom/ReflectionProbe-1.png
  Assets/Scenes/BossRoom/ReflectionProbe-1.png.meta
  Assets/Scenes/BossRoom/ReflectionProbe-2.png
  Assets/Scenes/BossRoom/ReflectionProbe-2.png.meta
  Assets/Scenes/BossRoom/ReflectionProbe-3.exr.meta
  CHANGELOG.md
Labels: 0-URGENT, 3-Good to Merge

#713 Feature: Quality Settings Pass [MTT-4450]
  Assets/Prefabs/Game/InteractiveFloorSwitch.prefab
  Assets/Prefabs/GameCam/Main Camera.prefab
  Assets/Prefabs/Shadow.prefab
  Assets/URP/Mobile/0_UniversalRenderPipelineAsset_Mobile_Low.asset
  Assets/URP/Mobile/0_UniversalRenderPipelineAsset_Mobile_Low.asset.meta
  Assets/URP/Mobile/0_UniversalRenderPipelineAsset_Renderer_Mobile_Low.asset
  Assets/URP/Mobile/0_UniversalRenderPipelineAsset_Renderer_Mobile_Low.asset.meta
  Assets/URP/Mobile/1_UniversalRenderPipelineAsset_Mobile_Medium.asset
  Assets/URP/Mobile/1_UniversalRenderPipelineAsset_Mobile_Medium.asset.meta
  Assets/URP/Mobile/1_UniversalRenderPipelineAsset_Renderer_Mobile_Med.asset
  Assets/URP/Mobile/1_UniversalRenderPipelineAsset_Renderer_Mobile_Med.asset.meta
  Assets/URP/Mobile/2_UniversalRenderPipelineAsset_Mobile_High.asset
  Assets/URP/Mobile/2_UniversalRenderPipelineAsset_Mobile_High.asset.meta
  Assets/URP/Mobile/2_UniversalRenderPipelineAsset_Renderer_Mobile_High.asset
  Assets/URP/Mobile/2_UniversalRenderPipelineAsset_Renderer_Mobile_High.asset.meta
  Assets/URP/Mobile/UniversalRenderPipelineAsset_Mobile_High.asset
  Assets/URP/Mobile/UniversalRenderPipelineAsset_Mobile_Low.asset
  Assets/URP/Mobile/UniversalRenderPipelineAsset_Mobile_Medium.asset
  Assets/URP/Mobile/UniversalRenderPipelineAsset_Renderer_Mobile_High.asset
  Assets/URP/Mobile/UniversalRenderPipelineAsset_Renderer_Mobile_Low.asset
  Assets/URP/Mobile/UniversalRenderPipelineAsset_Renderer_Mobile_Med.asset
  Assets/URP/PostProcessProfile.asset
  Assets/URP/Windows.meta
  Assets/URP/Windows/0_UniversalRenderPipelineAsset_Windows_Low.asset
  Assets/URP/Windows/0_UniversalRenderPipelineAsset_Windows_Low.asset.meta
  Assets/URP/Windows/0_UniversalRenderPipelineAsset_Windows_Low_Renderer.asset
  Assets/URP/Windows/0_UniversalRenderPipelineAsset_Windows_Low_Renderer.asset.meta
  Assets/URP/Windows/1_UniversalRenderPipelineAsset_Windows_Medium.asset
  Assets/URP/Windows/1_UniversalRenderPipelineAsset_Windows_Medium.asset.meta
  Assets/URP/Windows/1_UniversalRenderPipelineAsset_Windows_Medium_Renderer.asset
  Assets/URP/Windows/1_UniversalRenderPipelineAsset_Windows_Medium_Renderer.asset.meta
  Assets/URP/Windows/2_UniversalRenderPipelineAsset_Windows_High.asset
  Assets/URP/Windows/2_UniversalRenderPipelineAsset_Windows_High.asset.meta
  Assets/URP/Windows/2_UniversalRenderPipelineAsset_Windows_High_Renderer.asset
  Assets/URP/Windows/2_UniversalRenderPipelineAsset_Windows_High_Renderer.asset.meta
  Assets/URP/Windows/3_UniversalRenderPipelineAsset_Windows_Ultra.asset
  Assets/URP/Windows/3_UniversalRenderPipelineAsset_Windows_Ultra.asset.meta
  Assets/URP/Windows/3_UniversalRenderPipelineAsset_Windows_Ultra_Renderer.asset
  Assets/URP/Windows/3_UniversalRenderPipelineAsset_Windows_Ultra_Renderer.asset.meta
  Assets/UniversalRenderPipelineGlobalSettings.asset
  Assets/VFX/Prefabs/Environment/FX_Torch_Fire.prefab
  Assets/VFX/Prefabs/Environment/fx_ImpSpawner.prefab
  CHANGELOG.md
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/QualitySettings.asset
  ProjectSettings/TagManager.asset
Labels: 0-URGENT, 3-Good to Merge

#723 fix: spawned NetworkObjects despawn with additive scene
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/NetworkObjectSpawner.cs
Labels: 2-Easy, 3-Good to Merge

#724 fix: synced WinState was causing issues on a replay attempt (MTT-4490)
  Assets/Prefabs/State/PostGameState.prefab
  Assets/Scenes/BossRoom.unity
  Assets/Scripts/ApplicationLifecycle/ApplicationController.cs
  Assets/Scripts/Gameplay/GameState/PersistentGameState.cs
  Assets/Scripts/Gameplay/GameState/PostGameStateData.cs
  Assets/Scripts/Gameplay/GameState/PostGameStateData.cs.meta
  Assets/Scripts/Gameplay/GameState/ServerBossRoomState.cs
  Assets/Scripts/Gameplay/GameState/ServerPostGameState.cs
  Assets/Scripts/Gameplay/UI/PostGameUI.cs
  CHANGELOG.md
Labels: 2-Easy, 2-One More Review
