Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2022-01, with the labels that each got.

#415 fix: improving UI during connection flow
  Assets/BossRoom/Scripts/Client/UI/MainMenuUI.cs
  Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Labels: Good to Merge

#431 feat: button to copy room name to clipboard
  Assets/BossRoom/Prefabs/UI/CharacterSelectCanvas.prefab
  Assets/BossRoom/Scripts/Client/UI/RoomNameBox.cs
Labels: Needs Review

#434 fix: session manager host data initialization order
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Labels: Easy, One More Review

#439 fix: smooth host movement cleanup
  Assets/BossRoom/Prefabs/Character/PlayerAvatar.prefab
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacter.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
  Assets/BossRoom/Scripts/Client/Game/Entity/ClientAvatarGuidHandler.cs
  Assets/BossRoom/Scripts/Client/UI/UIStateDisplayHandler.cs
Labels: Needs Review

#440 update to latest netcode
  Packages/manifest.json
  Packages/packages-lock.json
Labels: Good to Merge

#443 fix: soft sync error when loading PostGame scene on client
  Assets/BossRoom/Scenes/PostGame.unity
Labels: Good to Merge

#442 fix: host name not showing
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/SessionManager.cs
Labels: Easy, One More Review

#437 fix: boss stuck in trampling animation when player becomes invisible during windup
  Assets/BossRoom/Models/Animation Controllers/CharacterSetController.controller
Labels: One More Review

#428 feat: cancel during join or host
  Assets/BossRoom/Scripts/Client/UI/MainMenuUI.cs
  Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Labels: Good to Merge

#433 fix: join code not displayed for clients using Unity Relay
  Assets/BossRoom/Scripts/Client/UI/RoomNameBox.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityRelayUtilities.cs
Labels: Easy, Good to Merge

#444 feat: cheat window
  Assets/BossRoom/Prefabs/DebugCheatsManager.prefab
  Assets/BossRoom/Prefabs/DebugCheatsManager.prefab.meta
  Assets/BossRoom/Prefabs/Game/StaticNetworkObjects/GlobalStaticNetworkObjects.prefab
  Assets/BossRoom/Prefabs/State/BossRoomState.prefab
  Assets/BossRoom/Prefabs/UI/BossRoomHudCanvas.prefab
  Assets/BossRoom/Prefabs/UI/MenuBtn.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scripts/DebugCheats.meta
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs.meta
  Assets/BossRoom/Scripts/DebugCheats/com.unity.multiplayer.samples.bossroom.debug.cheats.asmdef
  Assets/BossRoom/Scripts/DebugCheats/com.unity.multiplayer.samples.bossroom.debug.cheats.asmdef.meta
  Assets/BossRoom/Scripts/Server/ServerTestingHotkeys.cs
Labels: One More Review

#445 fix: default sound too high
  Assets/BossRoom/Scripts/Shared/ClientPrefs.cs
Labels: Easy, Good to Merge

#438 feat: move session manager and relay utilities to utilities package
  Assets/BossRoom/Prefabs/SessionManager.prefab
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/UnityRelayUtilities.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/UnityRelayUtilities.cs.meta
Labels: Easy, One More Review

#430 feat: god mode cheat
  Assets/BossRoom/Prefabs/UI/AllyHUD.prefab
  Assets/BossRoom/Prefabs/UI/BossRoomHudCanvas.prefab
  Assets/BossRoom/Prefabs/UI/CheatsPopupPanel.prefab
  Assets/BossRoom/Prefabs/UI/CheatsPopupPanel.prefab.meta
  Assets/BossRoom/Prefabs/UI/PartyHUD.prefab
  Assets/BossRoom/Scenes/BossRoom.unity
  Assets/BossRoom/Scripts/Client/UI/PartyHUD.cs
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Shared/NetworkLifeState.cs
Labels: One More Review

#454 fix: hitpoint depletion inconsistency with clamped values
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerBreakableLogic.cs
Labels: Easy, One More Review
