Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2022-09, with the labels that each got.

#725 Fix: Deleting Unneeded Animators
  Assets/VFX/Prefabs/Caster/FX_caster_skill_2.prefab
  Assets/VFX/Prefabs/Imp/FX_IMP_attack_1_Slash.prefab
  Assets/VFX/Prefabs/Imp/TossAttack/FX_IMP_TossAttack_Sparks.prefab
  Assets/VFX/Prefabs/Rogue/FX_RogueSkill2_end.prefab
  Assets/VFX/Prefabs/Rogue/FX_Rogue_attack_1_Slash.prefab
  Assets/VFX/Prefabs/Shared Hero FX/FX_Ice_Pieces.prefab
Labels: 2-Easy, 3-Good to Merge

#728 feat: reducing MaxPacketQueueSize to 256 [MTT-4595]
  Assets/Prefabs/NetworkingManager.prefab
  CHANGELOG.md
Labels: 2-Easy, 1-Needs Review

#726 fix: ClientNetworkTransform fix with 1.0.1+ changes main
  Assets/Scripts/Gameplay/Input/ClientClickFeedback.cs
  Assets/Scripts/Utils/NetworkOverlay/NetworkStats.cs
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkTransform.cs
  Packages/com.unity.multiplayer.samples.coop/package.json
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#729 Feature: Pickup Action Art and Sound Polish [MTT-4615] [MTT-4304]
  Assets/GameData/Action/General/Drop.asset
  Assets/GameData/Action/General/Pick Up.asset
  Assets/Models/Animation Controllers/CharacterSetController.controller
  Assets/Prefabs/Dungeon/Dungeon Pieces/pots/env_pot_heavy.prefab
  Assets/Prefabs/Dungeon/EnvLighting_Realtime.prefab
  Assets/Prefabs/Game/PickUpPot.prefab
  Assets/Scenes/BossRoom/DungeonBossRoom.unity
  Assets/Scenes/BossRoom/DungeonEntrance.unity
  Assets/Scenes/BossRoom/DungeonTransition.unity
  Assets/Scripts/Gameplay/GameplayObjects/ClientPickUpPotEffects.cs
  Assets/Scripts/Gameplay/GameplayObjects/ClientPickUpPotEffects.cs.meta
  Assets/Sounds/Env/drop_pot.wav
  Assets/Sounds/Env/drop_pot.wav.meta
  Assets/Sounds/Env/pickup_pot.wav
  Assets/Sounds/Env/pickup_pot.wav.meta
  Assets/Textures/UI/ui_action_pickup.png
  Assets/Textures/UI/ui_action_pickup.png.meta
  Assets/Textures/UI/ui_action_putdown.png
  Assets/Textures/UI/ui_action_putdown.png.meta
  Assets/VFX/Prefabs/Shared Hero FX/FX_DropObjectPoof.prefab
  Assets/VFX/Prefabs/Shared Hero FX/FX_DropObjectPoof.prefab.meta
  CHANGELOG.md
Labels: 2-Easy, 3-Good to Merge

#735 Fix: bootstrap scene fix (MTT-3707)
  Assets/Scripts/Editor/SceneBootstrapper.cs
  CHANGELOG.md
Labels: 0-URGENT, 3-Good to Merge

#738 fix: better instructions for hosting ip [MTT-4617]
  Assets/Prefabs/UI/IPPopup.prefab
  CHANGELOG.md
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#741 fix: fixing warnings when doing golden path [MTT-4658]
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientReconnectingState.cs
Labels: 0-URGENT, 2-Easy, 2-One More Review

#742 fix: shield charge trigger reset & reuse cooldown populated [MTT-4100]
  Assets/GameData/Action/Tank/TankShieldBuff.asset
  Assets/Scripts/Gameplay/Action/ConcreteActions/ChargedShieldAction.cs
  CHANGELOG.md
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#737 feat: upgrade lobby [MTT-3962][MTT-4105][MTT-4052]
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientReconnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
  Assets/Scripts/UnityServices/Lobbies/LobbyAPIInterface.cs
  Assets/Scripts/UnityServices/Lobbies/LobbyServiceFacade.cs
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/UnityRelayUtilities.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 0-URGENT, 3-Good to Merge

#740 chore: bump unity 2021.3.10f1
  CHANGELOG.md
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/BurstAotSettings_Android.json
  ProjectSettings/BurstAotSettings_StandaloneOSX.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
Labels: 0-URGENT, 2-Easy, 2-One More Review

#744 fix: argument null exception when clicking the lobby join button without a join code entered [MTT-4760]
  Assets/Prefabs/UI/LobbyUI.prefab
  Assets/Scripts/Gameplay/UI/Lobby/LobbyJoiningUI.cs
  CHANGELOG.md
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#743 fix: VandalImp tossed item only affects players and damage bumped [MTT-4762]
  Assets/Prefabs/Game/ImpTossedItem.prefab
Labels: 2-Easy, 3-Good to Merge

#745 Fix: Broken Material References on Decorative Pots [MTT-4750]
  Assets/Prefabs/Dungeon/Dungeon Pieces/pots/env_pot_heavy.prefab
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#747 fix: adding RTT graph to RNSM [MTT-4788]
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/CustomNetStatsMonitorConfiguration.asset
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/CustomNetStatsMonitorConfiguration.asset.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/NetStatsMonitorPrefab.prefab
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#749 Fix: Changed Default Quality Setting to Medium
  ProjectSettings/QualitySettings.asset
Labels: 2-Easy, 2-One More Review

#751 Feat: Char Portrait Mouse Hover Feedback [MTT-4754]
  Assets/Prefabs/UI/PlayerSeatTemplate.prefab
  Assets/Textures/UI/ui_archer_symbol_inactive.png
  Assets/Textures/UI/ui_archer_symbol_inactive.png.meta
  Assets/Textures/UI/ui_mage_symbol_inactive.png
  Assets/Textures/UI/ui_rogue_symbol_inactive.png
  Assets/Textures/UI/ui_tank_symbol_inactive.png
Labels: 2-Easy, 3-Good to Merge

#736 Adding TOC and index to readme [MTT-4617]
  .github/PULL_REQUEST_TEMPLATE.md
  Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
  CHANGELOG.md
  README.md
Labels: 0-URGENT, 3-Good to Merge

#752 fix: Moving utp to component instead of child GameObject
  Assets/Prefabs/NetworkingManager.prefab
  Assets/Scenes/Startup.unity
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#753 Fix: Reduction of SSAO Cost (Especially on Mac) [MTT-4558]
  Assets/Scenes/BossRoom.unity
  Assets/URP/PostProcessProfile.asset
  Assets/URP/Windows/1_UniversalRenderPipelineAsset_Windows_Medium_Renderer.asset
  Assets/URP/Windows/2_UniversalRenderPipelineAsset_Windows_High_Renderer.asset
  Assets/URP/Windows/3_UniversalRenderPipelineAsset_Windows_Ultra_Renderer.asset
  ProjectSettings/QualitySettings.asset
Labels: 0-URGENT, 2-Easy, 2-One More Review

#612 feat: PubSub improvement: ISubscriber unsub [MTT-2765]
  Assets/Scripts/Gameplay/GameState/ServerBossRoomState.cs
  Assets/Scripts/Gameplay/UI/IPConnectionWindow.cs
  Assets/Scripts/Gameplay/UI/IPUIMediator.cs
  Assets/Scripts/Gameplay/UI/Lobby/LobbyJoiningUI.cs
  Assets/Scripts/Gameplay/UI/Lobby/LobbyUIMediator.cs
  Assets/Scripts/Gameplay/UI/UnityServicesUIHandler.cs
  Assets/Scripts/Infrastructure/PubSub/IMessageChannel.cs
  Assets/Scripts/Infrastructure/PubSub/MessageChannel.cs
  CHANGELOG.md
Labels: 2-Easy, 2-Reviewed with Comments

#748 fix: lobby UI unblocking before it should [MTT-4579]
  Assets/Scripts/Gameplay/UI/Lobby/LobbyUIMediator.cs
  CHANGELOG.md
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#739 Fix: Hidden Archer VFX
  Assets/VFX/Prefabs/Archer/FX_Archer_skill1_cast_1.prefab
  Assets/VFX/Prefabs/Archer/FX_Archer_skill1_cast_2.prefab
  Assets/VFX/Prefabs/Archer/FX_Archer_skill1_cast_3.prefab
  Assets/VFX/Prefabs/Archer/fx_ChargingUpArrowFX.prefab
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#750 Fix: Smaller Arrow Trails [MTT-4770]
  Assets/VFX/Prefabs/Archer/FX_arrow.prefab
Labels: 0-URGENT, 2-Easy, 3-Good to Merge
