Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2022-04, with the labels that each got.

#574 fix: imps self-destroying on clients when late-joining with multiple additive scenes loaded
  Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Action/TargetActionFX.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
Labels: 2-Easy, 3-Good to Merge

#589 fix: alt-f4 not working while in lobby [MTT-3127]
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
Labels: 2-Easy, 3-Good to Merge

#590 fix: performance improvements (CPU-only)
  Assets/BossRoom/Scripts/Client/AnimationCallbacks/AnimatorFootstepSounds.cs
  Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs
  Assets/BossRoom/Scripts/Shared/Game/Action/ActionBase.cs
  Assets/BossRoom/Scripts/Shared/Net/NetworkStats.cs
Labels: 2-Easy, 3-Good to Merge

#583 fix: dead player not dead when reconnecting [MTT-2965]
  Assets/BossRoom/Scripts/Server/Game/Character/ServerAnimationHandler.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs
  Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs
Labels: 2-One More Review

#592 fix: fixing issue with iOS black screen where message queue constructor would get stripped out [MTT-2663]
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Infrastructure/DIScope.cs
  Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/MessageChannelDIExtensions.cs
Labels: 0-URGENT, 3-Good to Merge

#593 fix: arrow despawned rpc [MTT-3134]
  Assets/BossRoom/Scripts/Server/Game/Entity/ServerProjectileLogic.cs
Labels: 2-Easy, 2-One More Review

#510 feat: popup panel stacking
  Assets/BossRoom/Prefabs/UI/PopupPanel.prefab
  Assets/BossRoom/Prefabs/UI/PopupPanel.prefab.meta
  Assets/BossRoom/Prefabs/UI/SettingsPanelCanvas.prefab
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Client/UI/ConnectionStatusMessageUIManager.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/PopupManager.cs
  Assets/BossRoom/Scripts/Client/UI/PopupManager.cs.meta
  Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
Labels: 1-Needs Review

#595 chore/fix: remove online mode and IP/port from lobbies [MTT-3214]
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyCreationUI.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyListItemUI.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/RoomNameBox.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LocalLobby.cs
Labels: 2-One More Review

#596 MTT-3026 feat: Lobby and Authentication services to use async await
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Infrastructure/UpdateRunner.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Auth/AuthenticationServiceFacade.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Infrastructure/RateLimitCooldown.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Infrastructure/UnityServiceCallsTaskWrapper.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Infrastructure/UnityServiceCallsTaskWrapper.cs.meta
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/JoinedLobbyContentHeartbeat.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyAPIInterface.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Labels: 0-URGENT, 1-Needs Review

#581 fix: decoupling SessionManager from NetworkManager [MTT-2603]
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs
Labels: 2-One More Review

#585 feat: better lobby exception handling [MTT-2649]
  Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyJoiningUI.cs
  Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Labels: 2-Easy, 3-Good to Merge

#598 chore: bump ngo to pre.7 [MTT-3235]
  Assets/BossRoom/Scripts/Shared/Game/UI/Editor/NetworkLatencyWarning.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/TransportPicker.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 0-URGENT, 2-Easy, 3-Good to Merge

#597 fix: silencing errors that are not errors [MTT-2930] [MTT-3249]
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyAPIInterface.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs
Labels: 2-Easy, 1-Needs Review

#599 fix: Alpha4 input press doesn't open emote drawer on UI [MTT-3236]
  Assets/BossRoom/Scripts/Client/UI/HeroActionBar.cs
Labels: 2-Easy, 1-Needs Review

#602 fix: only server finds navigation object, asserts refactored [MTT-3248]
  Assets/BossRoom/Scripts/Client/UI/UIStateDisplayHandler.cs
  Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs
Labels: 2-Easy, 1-Needs Review

#600 bumping version and cleaning up dependencies for MTT-3250
  Packages/com.unity.multiplayer.samples.coop/package.json
  Packages/packages-lock.json
Labels: 2-Easy, 1-Needs Review

#603 chore: Adding @here in slack message for leak detection
  .github/workflows/leak_detect.yml
Labels: 2-Easy, 2-One More Review

#427 feat: loading screen
  Assets/BossRoom/Prefabs/SceneLoader.prefab
  Assets/BossRoom/Prefabs/SceneLoader.prefab.meta
  Assets/BossRoom/Prefabs/UI/LoadingScreen.prefab
  Assets/BossRoom/Prefabs/UI/LoadingScreen.prefab.meta
  Assets/BossRoom/Scenes/Startup.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientCharSelectState.cs
  Assets/BossRoom/Scripts/Client/UI/PostGameUI.cs
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
  Assets/BossRoom/Scripts/DebugCheats/com.unity.multiplayer.samples.bossroom.debug.cheats.asmdef
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ClientLoadingScreen.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ClientLoadingScreen.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ServerAdditiveSceneLoader.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ServerAdditiveSceneLoader.cs.meta
Labels: 3-Good to Merge

#608 fix: add Unity Gaming Services info to readmes [MTT-3263]
  Assets/Readme.asset
  README.md
Labels: 2-Easy, 2-One More Review

#607 feat: Added popup that tells users to set up project id if it's not set up [MTT-3265][MTT-3237]
  Assets/BossRoom/Scenes/MainMenu.unity
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Labels: 2-Easy, 3-Good to Merge

#610 fix: scene loading issue when shutting down [MTT-2828]
  Assets/BossRoom/Scenes/PostGame.unity
  Assets/BossRoom/Scripts/Client/UI/PostGameUI.cs
  Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
  Assets/BossRoom/Scripts/Shared/ApplicationController.cs
  Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
Labels: 2-Easy, 3-Good to Merge

#604 fix: relogin when auth token is stale [MTT-3253]
  Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
  Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
  Assets/BossRoom/Scripts/Shared/Net/UnityServices/Auth/AuthenticationServiceFacade.cs
Labels: 3-Good to Merge

#614 feat: bump tools version for perf improvements
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 0-URGENT, 2-Easy, 1-Needs Review

#615 chore: upgrade to 2020.3.33f1 LTS
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
Labels: 2-Easy, 1-Needs Review

#619 chore: adding optional pre-commit hooks [MTT-3302]
  RepoUtilities/InstallHooks.bat
  RepoUtilities/InstallHooks.sh
  RepoUtilities/pre-commit.py
  RepoUtilities/pre-commit.toInstall
Labels: 1-Needs Review

#623 chore: removing QoS
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 0-URGENT, 1-Needs Review

#625 fix: setting players unready when one leaves or joins
  Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
Labels: 2-Easy, 3-Good to Merge

#483 fix: SceneBootstrapper detects and allows TestRunner launches
  Assets/BossRoom/Scripts/Editor/SceneBootstrapper.cs
Labels: 2-Easy, 1-Needs Review

#616 Fix: Floor Tiles Z Fighting
  Assets/BossRoom/Prefabs/Dungeon/TransitionArea.prefab
  Assets/BossRoom/Scenes/BossRoom/DungeonTransition.unity
  Assets/BossRoom/Scenes/BossRoom/LightingData.asset
  Assets/BossRoom/Scenes/BossRoom/Lightmap-0_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-1_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-2_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-3_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-4_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/Lightmap-5_comp_light.exr
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-0.png
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-0.png.meta
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-1.png
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-1.png.meta
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-2.png
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-2.png.meta
  Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-3.exr.meta
Labels: 2-Easy, 3-Good to Merge

#605 feat: networked message channel
  Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/MessageChannel.cs
  Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/MessageChannelDIExtensions.cs
  Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/NetworkedMessageChannel.cs
  Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/NetworkedMessageChannel.cs.meta
Labels: 2-One More Review

#629 feat: client network transform move to samples [MTT-3406]
  Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/MessageChannelDIExtensions.cs
  Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/NetworkedMessageChannel.cs
  Assets/BossRoom/Scripts/Shared/NetworkNameState.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkTransform.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkTransform.cs.meta
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/com.unity.multiplayer.samples.utilities.clientauthority.asmdef
  Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/com.unity.multiplayer.samples.utilities.clientauthority.asmdef.meta
  Packages/com.unity.multiplayer.samples.coop/package.json
  Packages/packages-lock.json
Labels: 0-URGENT, 1-Needs Review, DO NOT MERGE

#631 fix: bump to pre.8 and fix compile issues [MTT-3413]
  Assets/BossRoom/Scripts/Shared/Game/GameEventMessage.cs
  Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/MessageChannelDIExtensions.cs
  Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/NetworkedMessageChannel.cs
  Assets/BossRoom/Scripts/Shared/NetworkNameState.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 0-URGENT, 1-Needs Review

#633 Update README.md with Utilities package ref
  README.md
Labels: 0-URGENT, 2-Easy, 1-Needs Review
