Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2023-08, with the labels that each got.

#854 Fix: Negative Collider Warning [MTT-6993]
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_diagonal_1.prefab
  Assets/Prefabs/Dungeon/Dungeon Pieces/env_wall1_base_diagonal_2.prefab
  CHANGELOG.md
Labels: 2-Easy, 1-Needs Review, type:bug

#855 feat: 2022.3.7f1 LTS upgrade [MTT-7093]
  .yamato/project.metafile
  Assets/URP/Mobile/0_UniversalRenderPipelineAsset_Renderer_Mobile_Low.asset
  Assets/VFX/Shaders/SG_Ice.shadergraph
  Assets/VFX/Shaders/SG_Sneaky.shadergraph
  CHANGELOG.md
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
Labels: 2-Easy, 1-Needs Review

#865 feat: upgrade project to NGO v1.6.0 [MTT-6875]
  Assets/Tests/Runtime/ConnectionManagementTests.cs
  Assets/Tests/Runtime/Unity.BossRoom.Tests.Runtime.asmdef
  CHANGELOG.md
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 2-Easy, 1-Needs Review

#860 feat: upgrade to lobby 1.1.0 [MTT-7092] [MTT-5665] [MTT-7101] [MTT-5708]
  Assets/Scripts/ConnectionManagement/ConnectionMethod.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/StartingHostState.cs
  Assets/Scripts/UnityServices/Lobbies/JoinedLobbyContentHeartbeat.cs
  Assets/Scripts/UnityServices/Lobbies/JoinedLobbyContentHeartbeat.cs.meta
  Assets/Scripts/UnityServices/Lobbies/LobbyAPIInterface.cs
  Assets/Scripts/UnityServices/Lobbies/LobbyServiceFacade.cs
  Assets/Scripts/UnityServices/Unity.BossRoom.UnityServices.asmdef
  CHANGELOG.md
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 3-Good to Merge

#863 fix: unable to quit application with application exit or in-game exit button [MTT-7003]
  Assets/Scripts/ApplicationLifecycle/ApplicationController.cs
  CHANGELOG.md
Labels: 2-Easy, 1-Needs Review

#862 fix: loading screen progress not always synced [MTT-6302]
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/LoadingProgressManager.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/NetworkedLoadingProgressTracker.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
Labels: 2-Easy, 1-Needs Review
