Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2023-04, with the labels that each got.

#821 fix: better input sanitization [MTT-5894]
  Assets/Prefabs/UI/IPPopup.prefab
  Assets/Scripts/Gameplay/UI/IPHostingUI.cs
  Assets/Scripts/Gameplay/UI/IPJoiningUI.cs
  Assets/Scripts/Gameplay/UI/IPUIMediator.cs
  CHANGELOG.md
Labels: 2-Easy, 1-Needs Review

#822 fix: Adding INetworkSerializeByMemcpy where recommended for network serialization [MTT-5912]
  Assets/Scripts/Gameplay/Action/ActionID.cs
  Assets/Scripts/Gameplay/GameState/NetworkCharSelection.cs
  Assets/Scripts/Infrastructure/NetworkGuid.cs
  CHANGELOG.md
  README.md
Labels: 2-Easy, 1-Needs Review

#824 refactor: replacing custom pool implementation with ObjectPool [MTT-6263]
  Assets/Scripts/Infrastructure/NetworkObjectPool.cs
  CHANGELOG.md
Labels: 1-Needs Review

#828 feat: upgrade to NGOv1.3.1 [MTT-6243]
  Assets/GameData/NetworkPrefabs.asset
  Assets/GameData/NetworkPrefabs.asset.meta
  Assets/Prefabs/NetworkingManager.prefab
  CHANGELOG.md
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/NetcodeForGameObjects.settings
Labels: 2-Easy, 2-Reviewed with Comments

#827 chore: network object pool cleanup
  Assets/Scripts/Infrastructure/NetworkObjectPool.cs
Labels: 2-Easy, 3-Good to Merge

#829 feat: Boss Room updated to NGO v1.4.0
  CHANGELOG.md
  Packages/manifest.json
  Packages/packages-lock.json
Labels: 3-Good to Merge

#831 feat: profile name authentication truncating [MTT-6241]
  Assets/Scripts/Gameplay/GameState/ClientMainMenuState.cs
  Assets/Scripts/Gameplay/UI/UIProfileSelector.cs
  Assets/Scripts/UnityServices/Auth/AuthenticationServiceFacade.cs
  Assets/Scripts/Utils/ProfileManager.cs
  CHANGELOG.md
Labels: 2-Easy, 3-Good to Merge

#830 fix: decoupling SceneLoaderWrapper and ConnectionStates [MTT-6242]
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
  Assets/Tests/Runtime/ConnectionManagementTests.cs
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
Labels: 2-Easy, 3-Good to Merge

#826 fix: fixing connection management test [MTT-4492][MTT-6242]
  Assets/Scripts/ConnectionManagement/ConnectionManager.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientReconnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ConnectionState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/StartingHostState.cs
  Assets/Tests/Runtime/ConnectionManagementTests.cs
  CHANGELOG.md
Labels: 3-Good to Merge

#833 feat: Boss Room bundle version upgraded, changelogs updated [MTT-6292]
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  ProjectSettings/ProjectSettings.asset
Labels: 1-Needs Review

#834 release v2.1.0: merge to main
  .yamato/mobile-build-and-run.yml
  Assets/GameData/NetworkPrefabs.asset
  Assets/GameData/NetworkPrefabs.asset.meta
  Assets/Prefabs/CharGFX/PlayerGraphics_Rogue.prefab
  Assets/Prefabs/CharGFX/PlayerGraphics_Tank.prefab
  Assets/Prefabs/Game/EnemySpawner.prefab
  Assets/Prefabs/NetworkingManager.prefab
  Assets/Prefabs/UI/IPPopup.prefab
  Assets/Scripts/ConnectionManagement/ConnectionManager.cs
  Assets/Scripts/ConnectionManagement/ConnectionMethod.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectedState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientReconnectingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/ConnectionState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/OnlineState.cs
  Assets/Scripts/ConnectionManagement/ConnectionState/StartingHostState.cs
  Assets/Scripts/Editor/BuildHelpers.cs
  Assets/Scripts/Editor/BuildHelpers.cs.meta
  Assets/Scripts/Gameplay/Action/ActionID.cs
  Assets/Scripts/Gameplay/GameState/ClientMainMenuState.cs
  Assets/Scripts/Gameplay/GameState/NetworkCharSelection.cs
  Assets/Scripts/Gameplay/GameplayObjects/Breakable.cs
  Assets/Scripts/Gameplay/GameplayObjects/Character/ClientCharacter.cs
  Assets/Scripts/Gameplay/GameplayObjects/EnemyPortal.cs
  Assets/Scripts/Gameplay/GameplayObjects/IDamageable.cs
  Assets/Scripts/Gameplay/UI/IPHostingUI.cs
  Assets/Scripts/Gameplay/UI/IPJoiningUI.cs
  Assets/Scripts/Gameplay/UI/IPUIMediator.cs
  Assets/Scripts/Gameplay/UI/RoomNameBox.cs
  Assets/Scripts/Gameplay/UI/UIProfileSelector.cs
  Assets/Scripts/Infrastructure/NetworkGuid.cs
  Assets/Scripts/Infrastructure/NetworkObjectPool.cs
  Assets/Scripts/Infrastructure/UpdateRunner.cs
  Assets/Scripts/UnityServices/Auth/AuthenticationServiceFacade.cs
  Assets/Scripts/UnityServices/Lobbies/LobbyAPIInterface.cs
  Assets/Scripts/UnityServices/Lobbies/LobbyServiceFacade.cs
  Assets/Scripts/Utils/NetworkOverlay/NetworkStats.cs
  Assets/Scripts/Utils/ProfileManager.cs
  Assets/Tests/Runtime/ConnectionManagementTests.cs
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/NetcodeForGameObjects.settings
  ProjectSettings/ProjectSettings.asset
  README.md
Labels: 1-Needs Review
