Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2023-06, with the labels that each got.

#836 feat: NetworkTransforms throughout project optimized where possible [MTT-6312]
  Assets/Prefabs/Character/Character.prefab
  Assets/Prefabs/Character/PersistentPlayer.prefab
  Assets/Prefabs/Character/PlayerAvatar.prefab
  Assets/Prefabs/DebugCheatsManager.prefab
  Assets/Prefabs/Game/Arrow.prefab
  Assets/Prefabs/Game/ChargedArrow1.prefab
  Assets/Prefabs/Game/ChargedArrow2.prefab
  Assets/Prefabs/Game/ChargedArrow3.prefab
  Assets/Prefabs/Game/ImpTossedItem.prefab
  Assets/Prefabs/Game/PickUpPot.prefab
  Assets/Prefabs/GameCam/Main Camera.prefab
  Assets/Prefabs/LoadingProgressTracker.prefab
  Assets/Prefabs/NetworkObjectPool.prefab
  Assets/Prefabs/SceneLoader.prefab
  Assets/Prefabs/State/BossRoomState.prefab
  Assets/Prefabs/State/CharSelectState.prefab
  Assets/Prefabs/State/MainMenuState.prefab
  Assets/Prefabs/State/PostGameState.prefab
  Assets/Scenes/BossRoom.unity
  Assets/Scenes/Startup.unity
  CHANGELOG.md
Labels: 1-Needs Review

#844 deleted default network prefabs asset
  Assets/DefaultNetworkPrefabs.asset
  Assets/DefaultNetworkPrefabs.asset.meta
Labels: 2-Easy

#843 feat: adding NetworkSimulator [MTT-6084] [MTT-6083]
  Assets/Prefabs/UI/NetworkSimulator.prefab
  Assets/Prefabs/UI/NetworkSimulator.prefab.meta
  Assets/Scenes/Startup.unity
  Assets/Scripts/Gameplay/UI/IPUIMediator.cs
  Assets/Scripts/Gameplay/Unity.BossRoom.Gameplay.asmdef
  Assets/Scripts/Utils/NetworkOverlay/NetworkLatencyWarning.cs
  Assets/Scripts/Utils/NetworkSimulatorUIMediator.cs
  Assets/Scripts/Utils/NetworkSimulatorUIMediator.cs.meta
  Assets/Scripts/Utils/Unity.BossRoom.Utils.asmdef
  Assets/Textures/UI/ui_btn_disabled.png.meta
  CHANGELOG.md
  Packages/manifest.json
  Packages/packages-lock.json
  README.md
Labels: 1-Needs Review, 2-hard

#846 feat: updating changelogs, readme and project version
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/package.json
  ProjectSettings/ProjectSettings.asset
  README.md
Labels: 2-Easy, 1-Needs Review
