Repository Unity-Technologies/com.unity.multiplayer.samples.coop, pull requests merged in 2024-03, with the labels that each got.

#882 chore: keeping Yamato tests at 2022.3.14 until editor is upgraded
  .yamato/project.metafile
Labels: 0-URGENT, 1-Needs Review, 0-workaround

#881 Fix: Removed NetworkObject from Scene State Game Object [MTT-5234]
  Assets/Prefabs/State/MainMenuState.prefab
  Assets/Scenes/MainMenu.unity
  CHANGELOG.md
Labels: 2-Easy

#880 Fix: Added null reference check to ClientInputSender script [MTT-6672]
  Assets/Scripts/Gameplay/UserInput/ClientInputSender.cs
  CHANGELOG.md
Labels: 2-Easy

#883 feat: upgrade to NGO v1.8.1, conversion to universal Rpcs, utility assembly includes Unity.Collections [MTT-8188]
  Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectedState.cs
  Assets/Scripts/Gameplay/Action/ConcreteActions/AOEAction.cs
  Assets/Scripts/Gameplay/Action/ConcreteActions/ChargedLaunchProjectileAction.cs
  Assets/Scripts/Gameplay/Action/ConcreteActions/ChargedShieldAction.cs
  Assets/Scripts/Gameplay/Action/ConcreteActions/DashAttackAction.cs
  Assets/Scripts/Gameplay/Action/ConcreteActions/FXProjectileTargetedAction.cs
  Assets/Scripts/Gameplay/Action/ConcreteActions/LaunchProjectileAction.cs
  Assets/Scripts/Gameplay/Action/ConcreteActions/MeleeAction.cs
  Assets/Scripts/Gameplay/Action/ConcreteActions/StealthModeAction.cs
  Assets/Scripts/Gameplay/Action/ConcreteActions/TossAction.cs
  Assets/Scripts/Gameplay/Action/ConcreteActions/TrampleAction.cs
  Assets/Scripts/Gameplay/Action/Input/ChargedActionInput.cs
  Assets/Scripts/Gameplay/DebugCheats/DebugCheatsManager.cs
  Assets/Scripts/Gameplay/GameState/ClientCharSelectState.cs
  Assets/Scripts/Gameplay/GameState/NetworkCharSelection.cs
  Assets/Scripts/Gameplay/GameplayObjects/Character/ClientCharacter.cs
  Assets/Scripts/Gameplay/GameplayObjects/Character/ServerCharacter.cs
  Assets/Scripts/Gameplay/GameplayObjects/Projectiles/PhysicsProjectile.cs
  Assets/Scripts/Gameplay/GameplayObjects/TossedItem.cs
  Assets/Scripts/Gameplay/UserInput/ClientInputSender.cs
  Assets/Scripts/Utils/NetworkOverlay/NetworkStats.cs
  CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/LoadingProgressManager.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs
  Packages/com.unity.multiplayer.samples.coop/Utilities/com.unity.multiplayer.samples.utilities.asmdef
  Packages/com.unity.multiplayer.samples.coop/package.json
  Packages/manifest.json
  Packages/packages-lock.json
  README.md
Labels: 1-Needs Review
